Repository wrf-model/WRF, pull requests merged in 2018-11, with the labels that each got.

#687 Add time slot information in DA gts_omb_oma diagnostics
  var/da/da_obs_io/da_read_omb_tmp.inc
  var/da/da_obs_io/da_write_obs.inc
Labels: Enhancement, WRFDA

#680 MYNN PBL shcu combo bug
  share/module_check_a_mundo.F
Labels: bug, release_v4.0.2

#655 Prepare for the release of WRF-v4.0.2
  README
  inc/version_decl
Labels: release_v4.0.2

#677 mass redistribution between GOCART dust/sea salt and MOZAIC bins
  chem/module_optical_averaging.F
Labels: WRF Chem, bug, release_v4.0.2

#657 Bug fix in Noah LSM - divide by zero
  phys/module_sf_noahdrv.F
Labels: PHYSICS, bug, release_v4.0.2

#665 Bug fix in RUC LSM with MYJ PBL. Bug fix in RUC LSM for seasonal variation of LAI with .rdlai2d=.false.
  dyn_em/module_first_rk_step_part1.F
  dyn_nmm/module_PHYSICS_CALLS.F
  phys/module_sf_ruclsm.F
  phys/module_surface_driver.F
Labels: PHYSICS, bug, release_v4.0.2

#692 Add the option mp_physics=40 to README.namelist
  run/README.namelist
Labels: release_v4.0.2
