Repository wrf-model/WRF, pull requests merged in 2018-09, with the labels that each got.

#625 Fixed qc, qr, qi, qs, qg updates to WRF moist variables
  var/da/da_transfer_model/da_transfer_xatowrf.inc
Labels: bug

#624 Upgrade WRFDA RTTOV interface to v12.1
  compile
  var/da/da_radiance/da_get_innov_vector_rttov.inc
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_rttov.f90
  var/da/da_radiance/da_rttov_ad.inc
  var/da/da_radiance/da_rttov_direct.inc
  var/da/da_radiance/da_rttov_init.inc
  var/da/da_radiance/da_rttov_k.inc
  var/da/da_radiance/da_rttov_tl.inc
  var/da/da_radiance/module_radiance.f90
Labels: enhancement

#644 Update the crtm_coeffs_2.2.3 path per cheyenne file system restructuring
  var/run/crtm_coeffs
Labels: WRFDA, bug, release_v4.0.1

#599 Fix in DA to make the code consistent with formulation for sfc wind correction
  var/da/da_tools/da_mo_correction.inc
Labels: WRFDA, bug, release_v4.0.1

#639 Fix to assign proper radar rv/rf errors to avoid excessive check_max_iv prints
  var/da/da_obs_io/da_read_obs_radar.inc
  var/da/da_radar/da_get_innov_vector_radar.inc
Labels: WRFDA, bug, release_v4.0.1

#638 Fix for cloud/w BE rescaling for not-first outerloops
  var/da/da_minimisation/da_get_var_diagnostics.inc
  var/da/da_minimisation/da_minimisation.f90
  var/da/da_setup_structures/da_scale_background_errors.inc
  var/da/da_setup_structures/da_setup_be_regional.inc
Labels: WRFDA, bug, release_v4.0.1

#602 Fix convert_emiss compilation issue (#601)
  compile
Labels: WRF Chem, bug, release_v4.0.1
