Repository wrf-model/WRF, pull requests merged in 2018-10, with the labels that each got.

#620 Fix half vs full 1d coeffs for HVC in small_step
  dyn_em/module_small_step_em.F
Labels: Add to "known problems", bug, release_v4.0.1

#621 Remove repeated factor of (1+Rv/Rd Qv) in start_em, p computation
  dyn_em/start_em.F
Labels: Add to "known problems", bug, release_v4.0.1

#626 Correct a few wrong namelist options in namelist.input.fire
  test/em_real/namelist.input.fire
Labels: bug, release_v4.0.1

#605 bug fix: incorrect PSISAT sign change introduced with groundwater fixes
  phys/module_sf_noahmpdrv.F
Labels: PHYSICS, bug, release_v4.0.1

#645 bugfix: prevent excessive snow liquid water movement
  phys/module_sf_noahmplsm.F
Labels: PHYSICS, bug, release_v4.0.1

#646 bugfix: fix potential divide by zero in stomatal resistance diagnostic
  phys/module_sf_noahmpdrv.F
Labels: PHYSICS, bug, release_v4.0.1

#647 bugfix: add limit to Noah-MP leaf aerodynamic resistance
  phys/module_sf_noahmplsm.F
Labels: PHYSICS, bug, release_v4.0.1

#648 bugfix: array out of bounds occurs for certain Noah-MP options
  phys/module_sf_noahmplsm.F
Labels: PHYSICS, bug, release_v4.0.1

#649 several Thompson BF: reduced rain, increased ice conc, remove tiny precip, allow high model tops, higher min dust conc
  phys/module_mp_thompson.F
Labels: PHYSICS, bug, release_v4.0.1

#643 Update source code character string from v4.0 to v4.0.1
  inc/version_decl
Labels: release_v4.0.1

#661 Modification of README.namelist
  run/README.namelist
Labels: Enhancement

#640 Add DA namelist options for turning on/off some diagnostic output
  Registry/registry.var
  var/da/da_airep/da_airep.f90
  var/da/da_airep/da_check_max_iv_airep.inc
  var/da/da_airsr/da_airsr.f90
  var/da/da_airsr/da_check_max_iv_airsr.inc
  var/da/da_bogus/da_bogus.f90
  var/da/da_bogus/da_check_max_iv_bogus.inc
  var/da/da_buoy/da_buoy.f90
  var/da/da_buoy/da_check_max_iv_buoy.inc
  var/da/da_geoamv/da_check_max_iv_geoamv.inc
  var/da/da_geoamv/da_geoamv.f90
  var/da/da_gpspw/da_check_max_iv_gpspw.inc
  var/da/da_gpspw/da_gpspw.f90
  var/da/da_gpsref/da_check_max_iv_gpsref.inc
  var/da/da_gpsref/da_gpsref.f90
  var/da/da_main/da_solve.inc
  var/da/da_metar/da_check_max_iv_metar.inc
  var/da/da_metar/da_metar.f90
  var/da/da_minimisation/da_get_innov_vector.inc
  var/da/da_minimisation/da_minimisation.f90
  var/da/da_minimisation/da_write_diagnostics.inc
  var/da/da_mtgirs/da_check_max_iv_mtgirs.inc
  var/da/da_mtgirs/da_mtgirs.f90
  var/da/da_pilot/da_check_max_iv_pilot.inc
  var/da/da_pilot/da_pilot.f90
  var/da/da_polaramv/da_check_max_iv_polaramv.inc
  var/da/da_polaramv/da_polaramv.f90
  var/da/da_profiler/da_check_max_iv_profiler.inc
  var/da/da_profiler/da_profiler.f90
  var/da/da_qscat/da_check_max_iv_qscat.inc
  var/da/da_qscat/da_qscat.f90
  var/da/da_rain/da_check_max_iv_rain.inc
  var/da/da_rain/da_rain.f90
  var/da/da_satem/da_check_max_iv_satem.inc
  var/da/da_satem/da_satem.f90
  var/da/da_ships/da_check_max_iv_ships.inc
  var/da/da_ships/da_ships.f90
  var/da/da_sound/da_check_max_iv_sonde_sfc.inc
  var/da/da_sound/da_check_max_iv_sound.inc
  var/da/da_sound/da_sound.f90
  var/da/da_ssmi/da_check_max_iv_ssmi_rv.inc
  var/da/da_ssmi/da_check_max_iv_ssmt1.inc
  var/da/da_ssmi/da_check_max_iv_ssmt2.inc
  var/da/da_ssmi/da_ssmi.f90
  var/da/da_synop/da_check_max_iv_synop.inc
  var/da/da_synop/da_synop.f90
  var/da/da_tamdar/da_check_max_iv_tamdar.inc
  var/da/da_tamdar/da_check_max_iv_tamdar_sfc.inc
  var/da/da_tamdar/da_tamdar.f90
Labels: Enhancement, WRFDA

#641 Add DA namelist options for specifying errors for radar rhv(rrn/rsn/rgr)
  Registry/registry.var
  var/da/da_radar/da_get_innov_vector_radar.inc
  var/da/da_radar/da_radar.f90
Labels: Enhancement, WRFDA

#667 Bug fix in optical_prep_gocart
  chem/module_optical_averaging.F
  phys/module_data_gocart_dust.F
Labels: WRF Chem, bug, release_v4.0.2

#662 README for CRTM coefficient procedure
  doc/README.crtm
Labels: WRFDA

#663 Fix DA compilation when RTTOV-v11 is built with HDF5-enabled
  arch/Config.pl
  compile
Labels: WRFDA, bug, release_v4.0.2

#666 Add descriptions and units of constant variables
  share/module_model_constants.F
Labels: Enhancement

#673 BF: chemical reaction rate change: e-11 -> e-31
  chem/KPP/mechanisms/mozart/mozart.def
  chem/KPP/mechanisms/mozart_mosaic_4bin/mozart_mosaic_4bin.def
  chem/KPP/mechanisms/mozart_mosaic_4bin_aq/mozart_mosaic_4bin_aq.def
  chem/KPP/mechanisms/mozcart/mozcart.def
  chem/KPP/mechanisms/t1_mozcart/t1_mozcart.def
Labels: WRF Chem, bug, release_v4.0.2

#668 Bug fix: Cray compiler, character string, module_cu_mskf.F
  phys/module_cu_mskf.F
Labels: PHYSICS, bug, release_v4.0.2

#669 Bug fix: cray, nonrepresentable value, module_mp_morr_two_moment_aero.F
  phys/module_mp_morr_two_moment_aero.F
Labels: PHYSICS, bug, release_v4.0.2

#670 Bug fix: cray, do loop index is real, module_mp_morr_two_moment_aero.F
  phys/module_mp_morr_two_moment_aero.F
Labels: PHYSICS, bug, release_v4.0.2

#674 Fix zero-valued d02 dry potential temp pert, from horiz interpolation
  Registry/Registry.EM_COMMON
Labels: bug, release_v4.0.2

#675 Remove MPI build option from single column model (SCM)
  Makefile
  compile
Labels: bug, release_v4.0.2

#679 bug in G3 cu_physics - random seed array bounds errors
  phys/module_cu_g3.F
Labels: PHYSICS, bug, release_v4.0.2

#658 Add CODEOWNERS file to .github directory
  .github/CODEOWNERS
Labels: New Feature

#686 Fix DA formatted print of random_seed array when put_rand_seed=false
  var/da/da_define_structures/da_random_seed.inc
Labels: WRFDA, bug, release_v4.0.2
