Repository wrf-model/WRF, pull requests merged in 2018-12, with the labels that each got.

#702 Fix adjustment of urban type in REAL program when NLCD and MODIS used together
  dyn_em/module_initialize_real.F
Labels: bug, release_v4.0.3

#710 Error compiling WRF Plus in WRF 4.0.2 on module_wrf_top.f90
  main/module_wrf_top.F
Labels: bug, release_v4.0.3

#716 change calls from wrf_message to wrf_debug in module_quilt_outbuf_ops
  frame/module_quilt_outbuf_ops.F
Labels: Enhancement

#722 Adding hydro team to the CODEOWNERS file
  .github/CODEOWNERS
Labels: Enhancement

#721 Fix DA warning message for cv_options=3 and cloud_cv_options>0
  var/da/da_main/da_solve.inc
Labels: WRFDA, bug, release_v4.0.3

#717 BF: Fix registry for input geogrid fields that are missing either "i2" or "d"
  Registry/Registry.EM_COMMON
Labels: bug, release_v4.0.3

#698 Remove hard-coded max number of tasks for obs nudging
  external/RSL_LITE/module_dm.F
Labels: bug, release_v4.0.3

#724 Additional WRF/MPAS unification to reduce if-defs for MPAS-specific n…
  phys/module_bl_ysu.F
  phys/module_pbl_driver.F
Labels: Enhancement, PHYSICS

#723 Change DA namelist use_html default from true to false
  Registry/registry.var
Labels: Enhancement, WRFDA

#713 Reworded module_soil_pre error message for incorrect num_soil_layers
  share/module_soil_pre.F
Labels: Enhancement

#613 Add a flag that turns on/off soil moisture adjustment
  Registry/Registry.EM_COMMON
  dyn_em/module_initialize_real.F
  share/module_soil_pre.F
Labels: Enhancement, PHYSICS

#732 LES fix for use_theta_m=1
  dyn_em/module_diffusion_em.F
  dyn_em/module_first_rk_step_part2.F
Labels: Dynamics ARW, bug, release_v4.0.3

#737 Fix N^2 calculation (1.61->0.61) for LES
  dyn_em/module_diffusion_em.F
Labels: bug, release_v4.0.3

#735 reduce lines to less than 150 characters for github
  phys/module_microphysics_driver.F
Labels: PHYSICS, bug, release_v4.0.3

#636 identically matching MM5 code with MM5 MPAS PR
  phys/module_sf_sfclay.F
Labels: PHYSICS, UNIFY

#637 WSM6 change of refl_10cm to "optional" to work with mpas
  phys/module_mp_wsm6.F
Labels: PHYSICS, UNIFY
