Repository wrf-model/WRF, pull requests merged in 2019-03, with the labels that each got.

#807 mm5 sfclay adding 'defined(mpas)' to call to SFCLAY1D
  phys/module_sf_sfclay.F
Labels: PHYSICS

#806 Updates/comments added to Jensen_ISHMAEL microphysics
  phys/module_mp_jensen_ishmael.F
Labels: PHYSICS

#805 W[SD]M[67] accretion mods for freezing rain
  phys/module_mp_wdm6.F
  phys/module_mp_wdm7.F
  phys/module_mp_wsm6.F
  phys/module_mp_wsm7.F
Labels: PHYSICS

#809 WSM6: remove unnecessary ifdef for purpose of WRF/MPAS unification
  phys/module_mp_wsm6.F
Labels: Develop Branch, PHYSICS

#821 Update one and add two references to MSKF
  phys/module_cu_mskf.F
Labels: Comments Only, PHYSICS, release-v4.1

#823 PBLs: h1 constant should be 1/3, but was 0.33333335
  phys/module_bl_mynn.F
  phys/module_bl_shinhong.F
  phys/module_bl_ysu.F
Labels: PHYSICS, bug, release-v4.1

#808 Jensen look-up table files: Makefile (add links), clean (add removes)
  Makefile
  clean
Labels: PHYSICS, bug, release-v4.1

#797 Add FY3C-MWHS2 radiance DA capability
  Registry/registry.var
  var/da/da_obs_io/da_read_y_unit.inc
  var/da/da_radiance/da_qc_mwhs2.inc
  var/da/da_radiance/da_qc_rad.inc
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_radiance1.f90
  var/da/da_radiance/da_radiance_init.inc
  var/da/da_radiance/da_read_obs_hdf5mwhs2.inc
  var/da/da_radiance/da_read_pseudo_rad.inc
  var/da/da_radiance/da_setup_radiance_structures.inc
  var/da/da_radiance/module_radiance.f90
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_structures.f90
  var/run/VARBC.in
  var/run/radiance_info/fy3-3-mwhs2.info
Labels: Develop Branch, New Feature, WRFDA

#784 Helpful printout info: 1) gross check for d01 time step, 2) current and sim start date in printout
  Registry/Registry.EM_COMMON
  dyn_em/start_em.F
  share/input_wrf.F
Labels: Enhancement, release-v4.1

#793 Use linear vertical interpolation for pos def fields
  Registry/Registry.EM_COMMON
  dyn_em/module_initialize_real.F
Labels: Enhancement, release-v4.1

#804 Make random seeds for stochastic schemes able to be in restart file and be allocatable
  Registry/registry.dimspec
  Registry/registry.stoch
  dyn_em/module_first_rk_step_part2.F
  dyn_em/module_stoch.F
  share/module_check_a_mundo.F
Labels: bug, release-v4.1

#800 Deng convection scheme only works with MYJ or MYNN PBL, and deep convection must be turned off
  run/README.namelist
  share/module_check_a_mundo.F
Labels: PHYSICS, bug, release-v4.1

#776 Bug fix for RRTMG with o3input=2 option
  phys/module_radiation_driver.F
Labels: PHYSICS, bug, release-v4.1

#819 MYNN-EDMF: bug fix for mass-flux subgrid clouds, enhancement for non-conv subgrid clouds
  phys/module_bl_mynn.F
Labels: PHYSICS, release-v4.1

#822 KSAS: scale dependent trigger, conversion parameter, xmb trigger condition
  phys/module_cu_ksas.F
Labels: PHYSICS, release-v4.1

#818 updated P3 for WRF v4.1 (now at P3 version 3.1.11)
  phys/module_mp_p3.F
  phys/module_physics_init.F
  run/create_p3_lookupTable_1.f90
  run/p3_lookup_table_1.dat-v2.8.2
  run/p3_lookup_table_1.dat-v4.1
Labels: PHYSICS, release-v4.1

#812 Jensen Ishmael microphysics: updates for initial release
  phys/module_mp_jensen_ishmael.F
Labels: PHYSICS, release-v4.1

#817 Update parameters in icloud3, changes to AOD for Thompson-Eidhammer aerosol-aware scheme
  phys/module_radiation_driver.F
Labels: PHYSICS, release-v4.1

#820 Jensen microphysics: negative qi in vapor growth
  phys/module_mp_jensen_ishmael.F
Labels: PHYSICS, bug, release-v4.1

#826 Cray: gcc -> cc
  arch/configure.defaults
Labels: release-v4.1

#827 Bug Fix: use Noah-MP table roughness length in urban areas when using bulk scheme (no urban option used)
  phys/module_sf_noahmplsm.F
Labels: release-v4.1

#828 Bug Fix: fix some uninitialized Noah-MP variables
  phys/module_sf_noahmp_glacier.F
  phys/module_sf_noahmpdrv.F
  phys/module_sf_noahmplsm.F
Labels: release-v4.1

#833 SH2O had two appearances in call to ssttep routine
  phys/module_sf_noahlsm.F
Labels: PHYSICS, UNIFY

#832 Jensen Ishmael microphysics: additional update for initial release
  phys/module_mp_jensen_ishmael.F
Labels: PHYSICS, release-v4.1

#838 em_scm_xy compile bug fix: add 'flag_sm_adj' to call to process_soil_real in module_initialize_scm_xy
  dyn_em/module_initialize_scm_xy.F
Labels: release-v4.1

#829 Syntax errors: (a ** -b) becomes (a ** (-b)); in new Jensen and Goddard MP schemes
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_mp_jensen_ishmael.F
Labels: release-v4.1

#835 MP=8,28 initialize_real additions for cloud droplet number, cloud ice number, rain number
  dyn_em/module_initialize_real.F
Labels: PHYSICS, release-v4.1

#843 Jensen Ishmael microphysics: absolutely positively and definitely the final code update for initial release
  phys/module_mp_jensen_ishmael.F
Labels: PHYSICS, release-v4.1

#842 Remove 3ice Goddard option
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  main/depend.common
  phys/Makefile
  phys/module_microphysics_driver.F
  phys/module_mp_gsfcgce_3ice_nuwrf.F
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_physics_init.F
  run/README.namelist
  share/dfi.F
  share/module_check_a_mundo.F
Labels: Enhancement, PHYSICS, release-v4.1

#845 Add new option cldovrlp to README file
  run/README.namelist
Labels: PHYSICS, release-v4.1
