Repository wrf-model/WRF, pull requests merged in 2019-07, with the labels that each got.

#940 Fix compile script to print model version, due to new version_decl format
  compile
Labels: bug, release-v4.1.2

#946 README.namelist: Adding new option, correct changed option
  run/README.namelist
Labels: release-v4.1.2

#944 Relocate derived bucket assignment to conventional location
  dyn_em/namelist_remappings_em.h
  share/module_check_a_mundo.F
Labels: bug, release-v4.1.2

#947 update README and inc/version_decl for release-v4.1.2
  README
  inc/version_decl
Labels: release-v4.1.2

#956 Fix to make DA namelist alpha_std_dev act as intended for tuning flow-dependent B
  var/da/da_setup_structures/da_setup_background_errors.inc
Labels: WRFDA, bug, release-v4.1.3

#960 YSU PBL: check on flag_qi instead of present(rqiblten)
  phys/module_bl_ysu.F
Labels: PHYSICS, bug, release-v4.1.3

#955 check eta levels in ideal case
  dyn_em/module_initialize_ideal.F
Labels: release-v4.1.3
