Repository wrf-model/WRF, pull requests merged in 2019-05, with the labels that each got.

#887 A new cloud detection scheme based on Particle Filter
  Registry/registry.var
  var/build/depend.txt
  var/da/da_radiance/da_allocate_rad_iv.inc
  var/da/da_radiance/da_cloud_detect.inc
  var/da/da_radiance/da_cloud_detect_airs.inc
  var/da/da_radiance/da_crtm.f90
  var/da/da_radiance/da_get_innov_vector_crtm.inc
  var/da/da_radiance/da_initialize_rad_iv.inc
  var/da/da_radiance/da_qc_ahi.inc
  var/da/da_radiance/da_qc_airs.inc
  var/da/da_radiance/da_qc_goesimg.inc
  var/da/da_radiance/da_qc_iasi.inc
  var/da/da_radiance/da_radiance1.f90
  var/da/da_radiance/da_rttov.f90
Labels: Develop Branch, New Feature, WRFDA

#893 A fix for the cloud detection scheme based on Particle Filter and MMR
  var/da/da_radiance/da_cloud_detect.inc
Labels: Develop Branch, WRFDA, bug

#896 Fix DA dual-res hybrid significant different results with different n…
  var/build/depend.txt
  var/da/da_vtox_transforms/da_calc_flow_dependence_xa_adj_dual_res.inc
  var/da/da_vtox_transforms/da_dual_res_c2n_ad.inc
  var/da/da_vtox_transforms/da_vtox_transforms.f90
Labels: WRFDA, bug, release-v4.1.1

#897 logical "specified" should be defined before use in diff_6th_opt
  dyn_em/module_big_step_utilities_em.F
Labels: bug, release-v4.1.1

#898 Add commas to LANDUSE.TBL file, does not affect results
  run/LANDUSE.TBL
Labels: release-v4.1.1

#888 fix compiler-sensitive looping for random seeds initialization in stochastic processing
  dyn_em/module_stoch.F
Labels: bug, release-v4.1.1

#879 Force positive definite with small mass and number from RRTMG K, avoids floating exception
  phys/module_ra_effective_radius.F
Labels: PHYSICS, release-v4.1.1

#875 Add controlled stop when detect timing problems with lateral boundary data
  share/input_wrf.F
Labels: release-v4.1.1

#899 Fix DA EnVar unnecessary allocation to reduce memory requirement
  Registry/registry.var
  var/da/da_main/da_wrfvar_init2.inc
Labels: Enhancement, WRFDA, release-v4.1.1

#889 Add more developers to CODEOWNERS file
  .github/CODEOWNERS
Labels: Enhancement, release-v4.1.1

#908 Fix WRFDA dm_bcast interfaces
  var/build/depend.txt
  var/da/da_gpseph/da_gpseph.f90
  var/da/da_obs_io/da_obs_io.f90
  var/da/da_par_util/da_par_util.f90
  var/da/da_physics/da_physics.f90
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_radiance1.f90
  var/da/da_setup_structures/da_scale_background_errors_cv3.inc
  var/da/da_setup_structures/da_setup_structures.f90
  var/da/da_test/da_test.f90
  var/da/da_tools/da_wrf_interfaces.f90
  var/da/da_transfer_model/da_transfer_model.f90
  var/da/da_transfer_model/da_transfer_wrftoxb.inc
Labels: WRFDA, bug, release-v4.1.1

#912 New gen_be_v3 for generating ep (ensemble perturbation) and be (background error)
  var/gen_be_v3/README.gen_be_v3
  var/gen_be_v3/compile_casper
  var/gen_be_v3/compile_cheyenne
  var/gen_be_v3/gen_be_v3.F90
  var/gen_be_v3/util/combine_be_cv7.f90
Labels: Develop Branch, New Feature, WRFDA

#900 New DA ep_format option to read in ensemble perturbation (ep)
  Registry/registry.var
  var/build/depend.txt
  var/da/da_main/da_solve.inc
  var/da/da_main/da_wrfvar_top.f90
  var/da/da_setup_structures/da_setup_flow_predictors.inc
  var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc
  var/da/da_setup_structures/da_setup_flow_predictors_ep_format3.inc
  var/da/da_setup_structures/da_setup_structures.f90
Labels: Develop Branch, New Feature, WRFDA

#916 Bugfix for missing values in bufr files
  var/da/da_obs_io/da_read_obs_bufr.inc
Labels: WRFDA, bug, release-v4.1.1

#915 Add 1-d array placeholder for nens for broadcasting
  var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc
Labels: WRFDA, bug

#874 Identify which auxiliary file is missing - stop incorrectly blaming failures on wrfout metadata
  share/input_wrf.F
Labels: release-v4.1.1

#906 Enforce conditional use of IEEE Fortran 2003 capabilities in v4.1 Goddard schemes
  configure
  phys/module_checkerror.F
  phys/module_gocart_coupling.F
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_ra_goddard.F
Labels: bug, release-v4.1.1

#907 "CHUNK = 16" -> "chunk = 16": avoids arch/configure.defaults -DCHUNK compiler flag confusion
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_ra_goddard.F
Labels: bug, release-v4.1.1

#909 Local CPP includes should use quotes, not angle brackets
  frame/module_alloc_space.h
Labels: bug, release-v4.1.1

#910 Ishmael DFI package typo: should be dfi_qv
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.1.1
