Repository wrf-model/WRF, pull requests merged in 2019-06, with the labels that each got.

#914 Correct variable in the package of "do_trad_fields"
  Registry/registry.trad_fields
Labels: release-v4.1.1

#913 Correct some instructions in README.namelist
  run/README.namelist
Labels: release-v4.1.1

#918 Prepare for WRF-v4.1.1 release
  README
  inc/version_decl
Labels: release-v4.1.1

#901 Fix vertical refinement, broken from v4.0 through v4.1
  dyn_em/module_initialize_real.F
  dyn_em/nest_init_utils.F
  main/depend.common
  main/ndown_em.F
  share/module_check_a_mundo.F
Labels: bug, release-v4.1.1

#927 Fix DA serial compilation failure introduced in commit dba34646
  var/da/da_vtox_transforms/da_vtox_transforms.f90
Labels: WRFDA, bug

#926 Fix Radar DA memory leak
  var/da/da_define_structures/da_allocate_y.inc
  var/da/da_define_structures/da_allocate_y_radar.inc
  var/da/da_define_structures/da_deallocate_observations.inc
  var/da/da_define_structures/da_deallocate_y.inc
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_radar/da_transform_xtoy_radar_adj.inc
Labels: WRFDA, bug

#928 Fix 4DVAR compilation failure after commit 56d4bef4
  var/build/da_name_space.pl
Labels: WRFDA, bug

#933 Fix to allow proper QVAPOR analysis when mp_physics is not set in namelist.input
  Registry/registry.var
Labels: WRFDA, bug, release-v4.1.2

#942 Bug fix: diagnostics: in temperature computation, incorrectly remove moisture from DRY theta perturbation
  dyn_em/start_em.F
  phys/module_diag_trad_fields.F
Labels: bug, release-v4.1.2

#941 Bug fix: traditional fields diags, u and v are 2x too large
  phys/module_diag_trad_fields.F
Labels: bug, release-v4.1.2

#931 Fix to make restarts reproducible in nests when topo_shading is used
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.1.2

#925 Jensen ISHMAEL microphysics: Bug fixes
  phys/module_mp_jensen_ishmael.F
Labels: bug, release-v4.1.2
