Repository wrf-model/WRF, pull requests merged in 2019-11, with the labels that each got.

#1012 SMS3dTKE: Remove broken packaging for km_opt=5
  Registry/Registry.EM_COMMON
Labels: Develop Branch, PHYSICS, bug

#1013 Add missing "IF km_opt==5" tests for diag computations
  dyn_em/module_diffusion_em.F
Labels: Develop Branch, PHYSICS, bug

#989 OML: fix out of bounds print
  phys/module_sf_oml.F
Labels: bug, release-v4.1.3

#997 Bug fix for RRTMG shortwave radiation
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
  phys/module_ra_rrtmg_swk.F
Labels: release-v4.1.3

#991 Release v4.1.3 nssl mp update
  phys/module_mp_nssl_2mom.F
Labels: PHYSICS, bug, release-v4.1.3

#973 BF: Remove extra comma in write statement inside Jensen MP
  phys/module_mp_jensen_ishmael.F
Labels: bug, release-v4.1.3

#985 Fix conflict between obs nudging and Thompson microphysics
  phys/module_mp_thompson.F
Labels: bug, release-v4.1.3

#950 Namelist checks only to be conducted on "allowed" grids
  share/module_check_a_mundo.F
Labels: bug, release-v4.1.3

#982 Deng scheme fix for occasional blow-ups
  phys/module_shcu_deng.F
Labels: bug, release-v4.1.3

#948 Obs nudging diagnostic print fix
  phys/module_fddaobs_rtfdda.F
  share/wrf_fddaobs_in.F
Labels: bug, release-v4.1.3

#1001 Change S letter to E letter in text DIMENSION
  share/input_wrf.F
Labels: bug, release-v4.1.3

#977 max_ts_level should be .LE. the number of half levels
  run/README.tslist
  share/module_check_a_mundo.F
Labels: bug, release-v4.1.3

#957 MP Thompson: mean snow size init; limit max values of snow/graupel/cloud; terminal velocity for rimed snow
  phys/module_mp_thompson.F
Labels: PHYSICS, release-v4.1.3

#1014 Fire: fix vert index for half-levels
  phys/module_fr_fire_util.F
Labels: PHYSICS, WRF Fire, bug, release-v4.1.3

#1016 Add WSM7 and WDM7 to README.namelist
  run/README.namelist
Labels: release-v4.1.3

#904 Variational Bias Correction of TAMDAR T
  Registry/registry.var
  var/build/da.make
  var/build/depend.txt
  var/da/da_control/da_control.f90
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_main/da_solve.inc
  var/da/da_main/da_wrfvar_finalize.inc
  var/da/da_main/da_wrfvar_init2.inc
  var/da/da_main/da_wrfvar_top.f90
  var/da/da_minimisation/da_adjoint_sensitivity.inc
  var/da/da_minimisation/da_calculate_gradj.inc
  var/da/da_minimisation/da_calculate_j.inc
  var/da/da_minimisation/da_get_innov_vector.inc
  var/da/da_minimisation/da_get_var_diagnostics.inc
  var/da/da_minimisation/da_kmat_mul.inc
  var/da/da_minimisation/da_minimisation.f90
  var/da/da_minimisation/da_minimise_cg.inc
  var/da/da_minimisation/da_minimise_lz.inc
  var/da/da_minimisation/da_transform_vtoy.inc
  var/da/da_minimisation/da_transform_vtoy_adj.inc
  var/da/da_test/da_check_gradient.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar.f90
  var/da/da_varbc_tamdar/da_varbc_tamdar_adj.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_direct.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_init.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_precond.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_pred.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_tl.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_update.inc
  var/run/VARBC_TAMDAR.tbl
Labels: Develop Branch, New Feature, WRFDA

#984 fixed calculation of the dust gravitational flux
  chem/module_gocart_settling.F
Labels: WRF Chem, bug, release-v4.1.3

#1019 Update top-level README & version_decl for V4.1.3 release
  README
  inc/version_decl
Labels: release-v4.1.3
