Repository wrf-model/WRF, pull requests merged in 2019-04, with the labels that each got.

#844 Allow Deng shcu to work with deep cu, remove prints, edit README
  phys/module_shcu_deng.F
  run/README.namelist
  share/module_check_a_mundo.F
Labels: PHYSICS, release-v4.1

#855 wrf/mpas unified old MM5 commits pushed to unified_physics branch
  phys/module_sf_sfclay.F
Labels: Shared Physics, UNIFY

#856 wrf/mpas unified new_tiedtke commits pushed to unified_physics branch
  phys/module_cu_ntiedtke.F
Labels: Shared Physics, UNIFY

#857 wrf/mpas unified ysu commits pushed to unified_physics branch
  phys/module_bl_ysu.F
  phys/module_pbl_driver.F
Labels: Shared Physics, UNIFY

#858 wrf/mpas unified wsm6 commits pushed to unified_physics branch
  phys/module_mp_wsm6.F
Labels: Shared Physics, UNIFY

#861 RRTMG bug fix for o3input option 2
  phys/module_radiation_driver.F
Labels: PHYSICS, Shared Physics, UNIFY

#840 Remove the *.dSYM directories from Darwin when "clean" command issued
  clean
Labels: Enhancement, release-v4.1

#841 TSLIST: add pressure field to vertical profile output files
  Registry/Registry.EM_COMMON
  run/README.tslist
  share/wrf_timeseries.F
Labels: Enhancement, release-v4.1

#846 In top-level Makefile, put required run dir file links to test/em_real
  Makefile
Labels: PHYSICS, release-v4.1

#849 mp 8,28: qnr tendency, smallest size cloud ice, partially melted snow terminal velocity
  phys/module_mp_thompson.F
Labels: PHYSICS, bug, release-v4.1

#851 Handle lowest-level microphysics species in real.exe
  dyn_em/module_initialize_real.F
Labels: release-v4.1

#853 Add diagnostic dry theta - t0 to restart file
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.1

#839 Require monotonic vertical pressure decrease: test after hybrid vert coordinate calculation in real
  dyn_em/module_initialize_real.F
Labels: Enhancement, release-v4.1

#859 Generalize new Goddard radiation and MP schemes to partner with other schemes
  Registry/Registry.EM_COMMON
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_physics_init.F
  phys/module_ra_goddard.F
  phys/module_radiation_driver.F
  share/module_check_a_mundo.F
Labels: PHYSICS, release-v4.1

#852 Remove one unnecessary DA print introduced in a recent commit
  var/da/da_main/da_update_firstguess.inc
Labels: WRFDA, release-v4.1

#862 Removed unused alarm and clock from microphysics schemes
  phys/module_mp_gsfcgce.F
  phys/module_mp_lin.F
  phys/module_mp_morr_two_moment.F
  phys/module_mp_morr_two_moment_aero.F
  phys/module_mp_wdm5.F
  phys/module_mp_wdm6.F
  phys/module_mp_wdm7.F
  phys/module_mp_wsm5.F
  phys/module_mp_wsm6.F
  phys/module_mp_wsm7.F
Labels: PHYSICS, release-v4.1

#854 Fix to allow assimilation of SSMI TPW contained in prepbufr obs files
  var/da/da_obs_io/da_read_obs_bufr.inc
Labels: WRFDA, release-v4.1

#860 wrf/mpas unified 2d dx commits pushed to unified_physics branch
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  phys/module_cu_ntiedtke.F
  phys/module_cumulus_driver.F
  phys/module_physics_init.F
  phys/module_sf_sfclay.F
  phys/module_surface_driver.F
Labels: PHYSICS, Shared Physics, UNIFY

#836 BF: TSLIST broken for (i,j) with MPI rank > 1
  share/wrf_tsin.F
Labels: bug, release-v4.1

#864 Fix dependencies for AFWA diagnostics
  main/depend.common
Labels: bug, release-v4.1

#865 BF: Incorrect AFWA diagnostics packaging; symptom: model hangs on history output
  Registry/registry.afwa
  phys/module_diag_afwa.F
Labels: bug, release-v4.1

#869 Several "AFWA diagnostic" memory fixes
  Registry/registry.afwa
  phys/module_diag_afwa.F
  share/module_check_a_mundo.F
Labels: bug, release-v4.1

#878 Use urban modules to define run-time configuration dimensions
  Registry/Registry.EM_COMMON
  Registry/registry.dimspec
  phys/module_sf_bep.F
  phys/module_sf_bep_bem.F
  phys/module_sf_urban.F
  share/module_check_a_mundo.F
  test/em_real/examples.namelist
Labels: CHOOSE THIS ONE OR THAT ONE, release-v4.1

#881 BF: WRFPlus TL version of first_rk_step_part2 requires updated arguments to RAND_PERT_UPDATE
  wrftladj/module_first_rk_step_part2_tl.F
Labels: WRFPLus, release-v4.1

#883 Update WRFDA v4.1 READMEs
  doc/README.DA
  var/README.namelist
  var/README.radiance
  var/run/README
Labels: WRFDA, release-v4.1

#884 update README and inc/version_decl for release-v4.1
  README
  inc/version_decl
Labels: release-v4.1
