Repository wrf-model/WRF, pull requests merged in 2019-02, with the labels that each got.

#750 Make 3DVAR and hybrid-EnVar work with moist potential T
  var/da/da_main/da_med_initialdata_input.inc
  var/da/da_main/da_update_firstguess.inc
Labels: Enhancement, WRFDA

#757 Add Deng shallow convection scheme (shcu_physics=5)
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.dimspec
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  main/depend.common
  phys/Makefile
  phys/module_physics_addtendc.F
  phys/module_physics_init.F
  phys/module_radiation_driver.F
  phys/module_shallowcu_driver.F
  phys/module_shcu_deng.F
  run/README.namelist
Labels: New Feature, PHYSICS

#734 Add new variables to output files of traditional fields
  Registry/Registry.EM_COMMON
  Registry/registry.trad_fields
  dyn_em/start_em.F
  phys/module_diag_trad_fields.F
  phys/module_diagnostics_driver.F
Labels: Enhancement

#712 new tslist options for wider variety of usage
  Registry/Registry.EM_COMMON
  main/depend.common
  run/README.tslist
  share/Makefile
  share/module_string_tools.F
  share/wrf_timeseries.F
  share/wrf_tsin.F
Labels: Enhancement

#782 BF: tslist ij mods need to have NMM Registry support
  Registry/Registry.NMM
Labels: bug

#785 Adjust da_update_bc for Moist Theta
  var/da/da_update_bc/da_update_bc.f90
Labels: WRFDA, bug

#766 BF full landread.c file should not be compiled by default
  arch/Config.pl
  arch/postamble
Labels: bug

#767 Correct README for vert refinement: RRTM + Dudhia rad only, no HVC allowed
  test/em_real/examples.namelist
Labels: bug

#771 BF input_wrf.F: error messages now match nml variable names
  share/input_wrf.F
Labels: bug

#773 Reduce std out from ./clean
  chem/KPP/clean_kpp
  chem/KPP/kpp/kpp-2.1/test/Makefile
  chem/KPP/util/wkc/Makefile
  chem/KPP/util/write_decomp/Makefile
  clean
  external/Makefile
  external/RSL_LITE/makefile
  external/atm_ocn/Makefile
  external/esmf_time_f90/Makefile
  external/fftpack/fftpack5/Makefile
  external/io_esmf/makefile
  external/io_grib1/Makefile
  external/io_grib1/WGRIB/Makefile
  external/io_grib2/Makefile
  external/io_grib_share/Makefile
  external/io_int/makefile
  external/io_mcel/makefile
  external/io_netcdf/makefile
  external/io_phdf5/Makefile
  external/io_pio/Makefile
  external/io_pnetcdf/Makefile
  external/ioapi_share/makefile
  tools/CodeBase/Makefile
  var/Makefile
  var/external/bufr/Makefile
  var/external/crtm_2.3.0/libsrc/makefile
  var/external/crtm_2.3.0/makefile
  var/external/wavelet/makefile
  var/obsproc/Makefile
Labels: Enhancement

#775 In real, supply base pressure at full levels at model top
  dyn_em/module_initialize_real.F
Labels: bug

#779 Fix -j parallel make option for compile script
  compile
Labels: bug

#780 Multiple locations where t_2 is assumed pert dry theta
  dyn_em/nest_init_utils.F
  main/depend.common
  phys/module_diagnostics_driver.F
  share/dfi.F
  share/mediation_integrate.F
  share/track_driver.F
  share/wrf_timeseries.F
Labels: bug

#781 BF: AGL interpolation incorrect for zld diagnostics
  phys/module_diag_zld.F
Labels: bug

#786 Remove Goddard radiation nested OpenMP regions
  phys/module_ra_goddard.F
Labels: PHYSICS, bug

#606 Updates for completeness of gas initialization and plumerise
  chem/chemics_init.F
  chem/module_plumerise1.F
Labels: Enhancement, WRF Chem

#714 bug fix in GOCART gravitational settling
  chem/module_gocart_settling.F
Labels: WRF Chem, bug

#774 Correcting pointers for MEGAN emissions in CRIv2R5 scheme.
  chem/module_data_mgn2mech.F
Labels: WRF Chem, bug

#787 chem: Add Grell-Devenyi (GD) scheme if cu_diag = 1
  chem/chemics_init.F
  run/README.namelist
  share/module_check_a_mundo.F
Labels: WRF Chem, bug

#790 typo in WRF Chem chem/chemics_init.F
  chem/chemics_init.F
Labels: WRF Chem, bug

#791 Version update: 4.0.3 -> 4.1-alpha
  inc/version_decl
Labels: Enhancement

#788 Remove extraneous HVC comments in module_check_a_mundo
  share/module_check_a_mundo.F
Labels: bug

#789 Finish the quieting of "./clean -a"
  clean
  external/Makefile
  external/io_grib_share/build/library_rules.mk
  var/Makefile
  var/external/crtm_2.3.0/libsrc/makefile_clean
  var/external/crtm_2.3.0/makefile
Labels: Enhancement
