Repository wrf-model/WRF, pull requests merged in 2019-08, with the labels that each got.

#970 bug fix for mynn PBL restarts - not giving bit-for-bit results
  Registry/Registry.EM_COMMON
Labels: release-v4.1.3

#958 New DA namelist alpha_vertloc_opt to choose how to get the alpha_vertloc info
  Registry/registry.var
  frame/module_configure.F
  var/README.namelist
  var/build/depend.txt
  var/da/da_setup_structures/da_get_alpha_vertloc.inc
  var/da/da_setup_structures/da_setup_be_nmm_regional.inc
  var/da/da_setup_structures/da_setup_be_regional.inc
  var/da/da_setup_structures/da_setup_structures.f90
Labels: Develop Branch, Enhancement, WRFDA

#971 MYNN PBL restart differences: add restart output stream for el_pbl
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.1.3

#962 YSU fix for WSM3 and Kessler no-ice test
  phys/module_bl_ysu.F
Labels: PHYSICS, bug, release-v4.1.3

#967 Improve DA RANDOMCV capability
  Registry/registry.var
  var/README.namelist
  var/da/da_define_structures/da_initialize_cv.inc
  var/da/da_main/da_solve.inc
  var/da/da_main/da_wrfvar_top.f90
  var/da/da_tools/da_set_randomcv.inc
Labels: Develop Branch, WRFDA

#972 Add a scale-adaptive 3DTKE parameterization scheme as a subgrid mixing option
  Registry/Registry.EM_COMMON
  dyn_em/module_diffusion_em.F
  dyn_em/module_first_rk_step_part2.F
  dyn_em/solve_em.F
  run/README.namelist
  share/module_check_a_mundo.F
  test/em_real/examples.namelist
Labels: Develop Branch, New Feature, PHYSICS
