Repository wrf-model/WRF, pull requests merged in 2019-12, with the labels that each got.

#952 Fix incorrect use of whereis and which to find nf-config command
  configure
Labels: bug, release-v4.1.4

#1027 Bug fix for calculating effective radius of rain, snow, and graupel
  var/da/da_radiance/da_cld_eff_radius.inc
Labels: WRFDA, bug, release-v4.1.4

#1029 sfclayrev fix for divide by zero
  phys/module_sf_sfclayrev.F
Labels: PHYSICS, bug, release-v4.1.4
