Repository wrf-model/WRF, pull requests merged in 2019-01, with the labels that each got.

#489 New soil table
  run/SOILPARM.TBL_Kishne_2017
Labels: PHYSICS

#693 Goddard contributions for Radiation and MP schemes
  Makefile
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.chem
  clean
  dyn_em/depend.dyn_em
  dyn_em/module_first_rk_step_part1.F
  dyn_em/solve_em.F
  dyn_em/start_em.F
  main/depend.common
  phys/Makefile
  phys/module_checkerror.F
  phys/module_gocart_coupling.F
  phys/module_microphysics_driver.F
  phys/module_mp_gsfcgce_3ice_nuwrf.F
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_physics_init.F
  phys/module_ra_goddard.F
  phys/module_radiation_driver.F
  run/BROADBAND_CLOUD_GODDARD.bin
  run/README.namelist
  share/dfi.F
  share/module_check_a_mundo.F
Labels: New Feature, PHYSICS

#733 US EPA PX LSM updates
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_sf_pxlsm.F
  phys/module_surface_driver.F
  run/README.namelist
Labels: Enhancement, PHYSICS

#703 Simple way to see what fields are allocated in WRF system
  arch/postamble
  frame/module_alloc_space.h
  tools/gen_allocs.c
Labels: New Feature

#764 MYNN PBL (only) update
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_bl_mynn.F
  phys/module_pbl_driver.F
  phys/module_physics_addtendc.F
  share/module_check_a_mundo.F
Labels: Enhancement, PHYSICS

#748 Capability to prescribe building fraction for air conditioning in BEM urban model
  phys/module_sf_bep_bem.F
  phys/module_sf_urban.F
  run/URBPARM.TBL
Labels: Enhancement, PHYSICS
