Repository wrf-model/WRF, pull requests merged in 2020-04, with the labels that each got.

#1151 Last updates to MYNN-EDMF for v4.2
  phys/module_bl_mynn.F
Labels: Enhancement, PHYSICS, release-v4.2

#1152 FSBM: use existing package flag for T/F compute diagnostics
  dyn_em/solve_em.F
  phys/module_microphysics_driver.F
  phys/module_mp_fast_sbm.F
Labels: PHYSICS, bug, release-v4.2

#1153 Make dx constant, though 2d dx array exists
  phys/module_physics_init.F
Labels: Enhancement, PHYSICS, release-v4.2

#1154 Add vertical nesting checks: no hybrid vert coord, no feedback
  share/module_check_a_mundo.F
Labels: Enhancement, release-v4.2

#1149 Irrigation clean-up: syntax error, derived nml packaging, protect against div by 0
  Registry/Registry.EM_COMMON
  phys/module_irrigation.F
  share/module_check_a_mundo.F
Labels: PHYSICS, bug, release-v4.2

#1161 Adding a couple of users to the CODEOWNERS file
  .github/CODEOWNERS
Labels: release-v4.2

#1165 Remove unnecessary wind-turbine-1.tbl file from test/em_real
  test/em_real/wind-turbine-1.tbl
Labels: PHYSICS, release-v4.2

#1166 Add a few urban initial fields to restart file
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.2

#1155 FSBM: don't communicate global PARAMETER values to other MPI processes
  phys/module_mp_fast_sbm.F
Labels: PHYSICS, bug, release-v4.2

#1162 MP=28: avoid unintended constant aerosol distribution
  dyn_em/module_initialize_real.F
Labels: PHYSICS, bug, release-v4.2

#1164 Rename ESMF_FractionMod to WRF_ESMF_FractionMod
  external/esmf_time_f90/ESMF_Fraction.F90
  external/esmf_time_f90/ESMF_Mod.F90
  external/esmf_time_f90/ESMF_TimeInterval.F90
  external/esmf_time_f90/Meat.F90
Labels: bug, release-v4.2

#1168 If WRF model has sf_urban_physics==0, wrf_inputdxx metadata value is ignored
  share/input_wrf.F
  share/output_wrf.F
Labels: PHYSICS, bug, release-v4.2

#1170 Efficiency fix for nwp_diag reflectivity calculation
  dyn_em/solve_em.F
  phys/module_microphysics_driver.F
  phys/module_mp_nssl_2mom.F
  phys/module_mp_thompson.F
Labels: Enhancement, PHYSICS, release-v4.2

#1171 Better RELEASE NOTES guidelines
  .github/PULL_REQUEST_TEMPLATE
  tools/commit_form.txt
Labels: Comments Only, release-v4.2

#1174 Several FARMS radiation related bug fixes
  phys/module_physics_init.F
  phys/module_radiation_driver.F
  share/module_check_a_mundo.F
Labels: PHYSICS, bug, release-v4.2

#1176 Bug fix for MYNN-EDMF: .LE. -> .LT. (twice)
  phys/module_bl_mynn.F
Labels: PHYSICS, bug, release-v4.2

#1181 Bug fix for retrieval radar reflectivity DA
  var/da/da_radar/da_get_innov_vector_radar.inc
Labels: WRFDA, bug, release-v4.2

#1182 Bug fix for WRFPLUS with SBM
  compile
  wrftladj/solve_em_ad.F
Labels: WRFDA, WRFPLus, bug, release-v4.2

#1178 Update version number
  README
  inc/version_decl
Labels: release-v4.2
