Repository wrf-model/WRF, pull requests merged in 2020-02, with the labels that each got.

#1057 WDM scheme minor bug fixes
  phys/module_mp_wdm5.F
  phys/module_mp_wdm6.F
  phys/module_mp_wdm7.F
Labels: PHYSICS, bug, release-v4.1.4

#1073 fix entry for KSAS
  run/README.namelist
Labels: release-v4.1.4

#1070 Changing gwd_opt to a domain-dependent namelist
  Registry/Registry.EM_COMMON
  run/README.namelist
  share/module_check_a_mundo.F
  test/em_real/namelist.input
  test/em_real/namelist.input.global
  test/em_real/namelist.input.jan00
  test/em_real/namelist.input.jun01
Labels: Develop Branch, New Feature, PHYSICS, release-v4.2

#1067 Update to MYNN surface layer scheme
  dyn_em/module_first_rk_step_part1.F
  phys/module_sf_mynn.F
  phys/module_surface_driver.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#831 2d grid distance
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/start_domain_nmm.F
  phys/module_cu_ntiedtke.F
  phys/module_cumulus_driver.F
  phys/module_pbl_driver.F
  phys/module_physics_init.F
  phys/module_radiation_driver.F
  phys/module_sf_sfclay.F
  phys/module_shallowcu_driver.F
  phys/module_surface_driver.F
Labels: Develop Branch, PHYSICS, UNIFY, release-v4.2

#1076 YSU Modify Comment at Top to Match Unified Physics and MPAS
  phys/module_bl_ysu.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#1003 Careful cygwin support
  README
  arch/Config.pl
  arch/configure.defaults
  arch/postamble
  arch/preamble
  configure
  doc/README.cygwin.md
  external/io_netcdf/makefile
  tools/Makefile
Labels: Develop Branch, release-v4.2

#1025 Adding a fast surface shortwave parameterization (FARMS)
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/Makefile
  phys/module_ra_aerosol.F
  phys/module_ra_farms.F
  phys/module_radiation_driver.F
  run/README.namelist
Labels: Develop Branch, New Feature, PHYSICS, WPRP approved, release-v4.2

#792 Fuel moisture model
  Registry/registry.fire
  clean
  dyn_em/module_initialize_fire.F
  phys/module_fr_fire_core.F
  phys/module_fr_fire_driver.F
  phys/module_fr_fire_driver_wrf.F
  phys/module_fr_fire_model.F
  phys/module_fr_fire_phys.F
  phys/module_fr_fire_util.F
  test/em_fire/README.txt
  test/em_fire/create_links.sh
  test/em_fire/input_sounding_rain
  test/em_fire/namelist.fire_fmc
  test/em_fire/namelist.input_rain
  test/em_real/namelist.input.fire
Labels: Develop Branch, Enhancement, WRF Fire, release-v4.2

#919 nwp_diagnostics made compatible with adaptive time step
  phys/module_diag_misc.F
  phys/module_diagnostics_driver.F
Labels: Develop Branch, New Feature, release-v4.2

#1078 Bug fixes for DA stand-alone gen_be_v3 utility in develop branch
  var/gen_be_v3/README.gen_be_v3
  var/gen_be_v3/gen_be_v3.F90
Labels: Develop Branch, WRFDA, bug, release-v4.2

#1079 Replace module interfaces for netcdf and mpi
  dyn_nmm/module_HIFREQ.F
  dyn_nmm/module_initialize_real.F
  external/RSL_LITE/module_dm.F
  frame/module_bdywrite.F
  phys/module_gocart_coupling.F
  phys/module_physics_init.F
  phys/module_ra_cam_support.F
Labels: Develop Branch, release-v4.2

#1072 Handle possible locations for rpc/types.h
  configure
  share/landread.c
Labels: Develop Branch, Enhancement, bug, release-v4.2

#1080 Fix build and run of ARW caused Fire Fuel Model mods
  Registry/registry.fire
  phys/module_fr_fire_phys.F
  share/module_check_a_mundo.F
Labels: Develop Branch, WRF Fire, bug, release-v4.2

#1081 Fix broken NMM build caused by FARMS mods
  dyn_em/module_first_rk_step_part1.F
  phys/module_radiation_driver.F
Labels: Develop Branch, PHYSICS, bug, release-v4.2

#1077 Output standard U10/V10 from MYJSFC and QNSESFC schemes
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/module_PHYSICS_CALLS.F
  dyn_nmm/start_domain_nmm.F
  phys/module_physics_init.F
  phys/module_sf_myjsfc.F
  phys/module_sf_qnsesfc.F
  phys/module_surface_driver.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#1074 A fix for conservation of enthalpy in BMJ cumulus scheme
  phys/module_cu_bmj.F
Labels: Develop Branch, PHYSICS, bug, release-v4.2

#994 Adding convective momentum transport to MSKF
  dyn_em/module_first_rk_step_part2.F
  phys/module_cu_mskf.F
  phys/module_cumulus_driver.F
  phys/module_physics_addtendc.F
  phys/module_physics_init.F
Labels: Develop Branch, Enhancement, release-v4.2

#1088 Improve memory usage for DA gen_be_v3 and add another output reformatting tool
  var/gen_be_v3/README.gen_be_v3
  var/gen_be_v3/gen_be_v3.F90
  var/gen_be_v3/util/combine_be_cv7_ccv2.f90
Labels: Develop Branch, Enhancement, WRFDA

#921 Precipitating Convective Cloud (PCC): cloud-radiation feedbacks for BMJ Cumulus Scheme
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/module_PHYSICS_CALLS.F
  phys/module_cu_bmj.F
  phys/module_cumulus_driver.F
  phys/module_physics_init.F
  phys/module_radiation_driver.F
Labels: Develop Branch, New Feature, PHYSICS, release-v4.2

#1068 Update of P3 module
  phys/module_mp_p3.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#1086 Noah LSM update to include unified_physics branch mods on develop branch
  phys/module_sf_bem.F
  phys/module_sf_bep.F
  phys/module_sf_bep_bem.F
  phys/module_sf_noah_seaice.F
  phys/module_sf_noah_seaice_drv.F
  phys/module_sf_noahdrv.F
  phys/module_sf_noahlsm_glacial_only.F
  phys/module_sf_urban.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#1084 KLUGE - Option to avoid building RRTMK due to GNU problem
  arch/postamble
  phys/module_physics_init.F
  phys/module_ra_rrtmg_lwk.F
  phys/module_ra_rrtmg_swk.F
  phys/module_radiation_driver.F
  share/module_check_a_mundo.F
Labels: Develop Branch, Enhancement, New Feature, PHYSICS, release-v4.2

#1089 Add Makefile dependency for FARMS scheme
  main/depend.common
Labels: Develop Branch, PHYSICS, bug, release-v4.2

#1090 Fix WRFPlus compilation issue
  share/mediation_integrate.F
  wrftladj/module_diffusion_em_ad.F
Labels: Develop Branch, WRFPLus, bug, release-v4.2

#1091 New default setting for RRTMG FAST and RRTMG KIAPS: no compile
  arch/postamble
Labels: Develop Branch, PHYSICS, release-v4.2

#1083 RadarVar for directly assimilating radar reflectivity with ice-phase species
  Registry/registry.var
  var/build/depend.txt
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_main/da_solve.inc
  var/da/da_minimisation/da_minimisation.f90
  var/da/da_obs/da_fill_obs_structures_radar.inc
  var/da/da_obs/da_obs.f90
  var/da/da_obs_io/da_read_obs_radar.inc
  var/da/da_radar/da_get_innov_vector_radar.inc
  var/da/da_radar/da_radar.f90
  var/da/da_radar/da_radar_rf.inc
  var/da/da_radar/da_radzicevar.inc
  var/da/da_radar/da_radzicevar_adj.inc
  var/da/da_radar/da_radzicevar_cal_tl_fw4wetice.inc
  var/da/da_radar/da_radzicevar_calc_ice_abc.inc
  var/da/da_radar/da_radzicevar_dryice_adj.inc
  var/da/da_radar/da_radzicevar_dryice_tl.inc
  var/da/da_radar/da_radzicevar_parameter_zrx.inc
  var/da/da_radar/da_radzicevar_parameter_zxx.inc
  var/da/da_radar/da_radzicevar_pkx.inc
  var/da/da_radar/da_radzicevar_prepare_interceptpara.inc
  var/da/da_radar/da_radzicevar_prepare_mixingratios.inc
  var/da/da_radar/da_radzicevar_prepare_zmm_adj.inc
  var/da/da_radar/da_radzicevar_pxabk.inc
  var/da/da_radar/da_radzicevar_rain_adj.inc
  var/da/da_radar/da_radzicevar_rain_tl.inc
  var/da/da_radar/da_radzicevar_rhoair_tl.inc
  var/da/da_radar/da_radzicevar_sigma_in_abc.inc
  var/da/da_radar/da_radzicevar_tl.inc
  var/da/da_radar/da_radzicevar_upper_f.inc
  var/da/da_radar/da_radzicevar_virtual.inc
  var/da/da_radar/da_radzicevar_waterfraction.inc
  var/da/da_radar/da_radzicevar_wetice_adj.inc
  var/da/da_radar/da_radzicevar_wetice_tl.inc
  var/da/da_radar/da_transform_xtoy_radar.inc
  var/da/da_radar/da_transform_xtoy_radar_adj.inc
  var/da/da_setup_structures/da_setup_be_regional.inc
  var/da/da_setup_structures/da_setup_obs_structures_madis.inc
Labels: Develop Branch, New Feature, WRFDA, release-v4.2

#1095 Separating new_diagnostics from the rest in diag_misc module
  main/depend.common
  phys/Makefile
  phys/module_diag_misc.F
  phys/module_diag_nwp.F
  phys/module_diagnostics_driver.F
Labels: Develop Branch, Enhancement, release-v4.2

#951 Do not reinitialise SOA_VBS or SORGAM aerosols on restart
  chem/module_aerosols_soa_vbs.F
  chem/module_aerosols_sorgam.F
Labels: WRF Chem, bug

#1099 Update WRF-Hydro to version 5.1.2
  hydro/CPL/WRF_cpl/Makefile
  hydro/CPL/WRF_cpl/module_wrf_HYDRO.F
  hydro/Data_Rec/Makefile
  hydro/Data_Rec/module_RT_data.F
  hydro/Data_Rec/module_namelist.F
  hydro/Data_Rec/namelist.inc
  hydro/Data_Rec/rt_include.inc
  hydro/HYDRO_drv/Makefile
  hydro/HYDRO_drv/module_HYDRO_drv.F
  hydro/MPP/CPL_WRF.F
  hydro/MPP/Makefile
  hydro/MPP/module_mpp_ReachLS.F
  hydro/MPP/mpp_land.F
  hydro/Routing/Makefile
  hydro/Routing/Noah_distr_routing.F
  hydro/Routing/Overland/Makefile
  hydro/Routing/Overland/module_overland.F
  hydro/Routing/Overland/module_overland_control.F
  hydro/Routing/Overland/module_overland_mass_balance.F
  hydro/Routing/Overland/module_overland_routing_properties.F
  hydro/Routing/Overland/module_overland_streams_and_lakes.F
  hydro/Routing/Overland/overland_tests.F
  hydro/Routing/module_GW_baseflow.F
  hydro/Routing/module_HYDRO_io.F
  hydro/Routing/module_HYDRO_utils.F
  hydro/Routing/module_NWM_io.F
  hydro/Routing/module_NWM_io_dict.F
  hydro/Routing/module_RT.F
  hydro/Routing/module_UDMAP.F
  hydro/Routing/module_channel_routing.F
  hydro/Routing/module_gw_gw2d.F
  hydro/Routing/module_noah_chan_param_init_rt.F
  hydro/Routing/module_reservoir_routing.F
  hydro/arc/Makefile.mpp
  hydro/arc/macros.gordon
  hydro/arc/macros.gordon.debug
  hydro/arc/macros.mpp.IBM.xlf90_r
  hydro/arc/macros.mpp.gfort
  hydro/arc/macros.mpp.ifort
  hydro/arc/macros.mpp.ifort.luna
  hydro/arc/macros.mpp.ifort.theia
  hydro/arc/macros.mpp.linux
  hydro/arc/macros.mpp.mpiifort
  hydro/arc/macros.seq.IBM.xlf90_r
  hydro/arc/macros.seq.gfort
  hydro/arc/macros.seq.ifort
  hydro/arc/macros.seq.linux
  hydro/arc/macros.theia.debug
  hydro/arc/macros.yellowstone
  hydro/arc/macros.yellowstone.debug
  hydro/nudging/Makefile
  hydro/nudging/module_nudging_io.F
  hydro/nudging/module_stream_nudging.F
  hydro/template/HYDRO/hydro.namelist
  hydro/template/NoahMP/namelist.hrldas
  hydro/template/setEnvar.sh
  hydro/utils/Makefile
  hydro/utils/module_version.F
Labels: Develop Branch, Enhancement, WRF Hydro, bug, release-v4.2

#980 Three new surface irrigation parameterizations
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  dyn_em/solve_em.F
  dyn_em/start_em.F
  phys/Makefile
  phys/module_irrigation.F
  phys/module_microphysics_driver.F
  phys/module_physics_init.F
  phys/module_sf_noahdrv.F
  phys/module_sf_noahlsm.F
  phys/module_surface_driver.F
  run/README.namelist
  share/module_check_a_mundo.F
  test/em_real/examples.namelist
Labels: Develop Branch, New Feature, PHYSICS, release-v4.2

#1094 Fixing extra biomass burning mass aloft
  chem/module_chem_plumerise_scalar.F
Labels: Develop Branch, WRF Chem, bug, release-v4.2

#1097 A new version of the FAST (33 bins) Spectral-Bin Microphysics (FSBM)
  Makefile
  Registry/registry.em_shared_collection
  Registry/registry.polrad
  Registry/registry.sbm
  arch/postamble
  configure
  dyn_em/solve_em.F
  phys/Makefile
  phys/module_diag_nwp.F
  phys/module_diagnostics_driver.F
  phys/module_microphysics_driver.F
  phys/module_mp_SBM_polar_radar.F
  phys/module_mp_fast_sbm.F
  phys/module_physics_init.F
  share/module_check_a_mundo.F
Labels: Develop Branch, New Feature, PHYSICS, release-v4.2

#1100 Fix feedback for odd nest ratios > 3:1
  share/interp_fcn.F
Labels: Develop Branch, bug, release-v4.2

#1101 Check if STEPWTD==0 in NoahMP before mod(timestep,STEPWTD)
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  dyn_em/module_first_rk_step_part1.F
  phys/module_surface_driver.F
Labels: Develop Branch, PHYSICS, bug, release-v4.2

#1104 Updates to MYNN-EDMF and related modules
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_bl_mynn.F
  phys/module_pbl_driver.F
  phys/module_radiation_driver.F
Labels: Develop Branch, Enhancement, PHYSICS, bug, release-v4.2

#1110 Adding Solar diagnostics package
  Registry/Registry.EM_COMMON
  Registry/registry.em_shared_collection
  Registry/registry.solar_fields
  dyn_em/module_first_rk_step_part1.F
  main/depend.common
  phys/Makefile
  phys/module_diag_solar.F
  phys/module_diagnostics_driver.F
  phys/module_radiation_driver.F
  run/README.namelist
  run/README.tslist
  share/module_check_a_mundo.F
  share/wrf_timeseries.F
  test/em_real/examples.namelist
Labels: Develop Branch, New Feature, PHYSICS, release-v4.2

#1102 Clean up lightning option in chem registry
  Registry/registry.chem
  phys/module_lightning_driver.F
  run/README.namelist
  test/em_real/examples.namelist
Labels: Develop Branch, PHYSICS, WRF Chem, bug, release-v4.2

#1112 Check for the existence of input tables for mp=30 FSBM
  share/module_check_a_mundo.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2
