Repository wrf-model/WRF, pull requests merged in 2020-03, with the labels that each got.

#1114 Fixes so WRFPLUS builds with develop branch
  arch/postamble
  main/depend.common
  share/module_check_a_mundo.F
  wrftladj/solve_em_ad.F
Labels: Develop Branch, PHYSICS, WRFDA, WRFPLus, bug, release-v4.2

#1107 TSLIST: add ozone field to vertical profile output files
  Registry/registry.chem
  share/wrf_timeseries.F
Labels: Develop Branch, Enhancement, release-v4.2

#1117 Add number of tasks to WRF history global attributes
  share/output_wrf.F
Labels: Enhancement, release-v4.2

#1118 Fix nudging of temperature obs at edge of tile
  Registry/Registry.EM_COMMON
Labels: PHYSICS, bug, release-v4.2

#1119 Vertical integrations in FARMS fixed for the hybrid vertical coordinate
  dyn_em/module_first_rk_step_part1.F
  phys/module_ra_farms.F
  phys/module_radiation_driver.F
Labels: PHYSICS, bug, release-v4.2

#1125 Redo PR#997 based on suggestion from Mike Iacono
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
  phys/module_ra_rrtmg_swk.F
Labels: release-v4.2

#1130 Improved treatment of mixed phase clouds in FARMS
  phys/module_ra_farms.F
Labels: Enhancement, PHYSICS, release-v4.2

#1123 Only test for FSBM input files if the FSBM code is built
  share/module_check_a_mundo.F
Labels: Enhancement, PHYSICS, release-v4.2

#1127 Bug Fix for FAST (33 bins) Spectral-Bin Microphysics (FSBM)
  phys/module_microphysics_driver.F
  phys/module_mp_fast_sbm.F
Labels: PHYSICS, bug, release-v4.2

#1131 Allow DA and FSBM to peacefully coexist in same repo
  arch/postamble
  configure
Labels: PHYSICS, WRFDA, WRFPLus, bug, release-v4.2

#1132 Fix vertical integrations in Solar diagnostics package for hybrid vertical coordinate
  phys/module_diag_solar.F
  phys/module_diagnostics_driver.F
Labels: PHYSICS, bug, release-v4.2

#1133 Remove icloud dependency for qc_tot and qi_tot calc when Solar diagnostics package is activated
  phys/module_radiation_driver.F
Labels: PHYSICS, bug, release-v4.2

#1134 Recover two profiles for W and pressure and add start date to TS output
  Registry/Registry.EM_COMMON
  share/wrf_timeseries.F
Labels: bug, release-v4.2

#1135 Updated FSBM (33-bins) scheme -- bug fix for release v4.2
  Registry/registry.sbm
  phys/module_mp_fast_sbm.F
Labels: PHYSICS, bug, release-v4.2

#1138 Very minor change to Graupel Y-intercept parameter equation
  phys/module_diag_nwp.F
  phys/module_mp_thompson.F
Labels: PHYSICS, bug, release-v4.2

#1141 Make VEGPARM.TBL for RUC-USGS and RUC-MODIS consistent with RUC scheme
  run/SOILPARM.TBL
  run/VEGPARM.TBL
Labels: PHYSICS, bug, release-v4.2

#1142 Preventing MSKF to be used with 3DTKE option
  share/module_check_a_mundo.F
Labels: release-v4.2

#1126 Fix for horizontal diffusion of w (diff_opt=2)
  dyn_em/module_diffusion_em.F
  dyn_em/module_first_rk_step_part2.F
Labels: bug, release-v4.2

#1137 Updating info in README for namelists
  run/README.namelist
Labels: release-v4.2

#1111 Allow .f90 files in kpp folder
  .gitignore
  chem/KPP/kpp/kpp-2.1/.gitignore
Labels: Develop Branch, WRF Chem, bug, release-v4.2

#1113 Prevent 0 index in GOCART settling array
  chem/module_gocart_settling.F
Labels: Develop Branch, WRF Chem, bug, release-v4.2

#1146 Syntax fixes from HPE
  phys/module_cu_bmj.F
  phys/module_sf_mynn.F
Labels: PHYSICS, bug, release-v4.2

#1145 Add more checks for Deng shallow scheme
  run/README.namelist
  share/module_check_a_mundo.F
Labels: release-v4.2

#1148 ARW SAS is CU=95, not CU=4 (scaleaware for NMM)
  share/module_check_a_mundo.F
Labels: Enhancement, release-v4.2

#1139 AHI Cloud Detection based on IR Cloud Mask
  Registry/registry.var
  var/build/da.make
  var/build/depend.txt
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_physics/da_physics.f90
  var/da/da_physics/da_trop_wmo.inc
  var/da/da_radiance/da_allocate_rad_iv.inc
  var/da/da_radiance/da_crtm.f90
  var/da/da_radiance/da_deallocate_radiance.inc
  var/da/da_radiance/da_get_innov_vector_crtm.inc
  var/da/da_radiance/da_initialize_rad_iv.inc
  var/da/da_radiance/da_qc_ahi.inc
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_radiance1.f90
  var/da/da_radiance/da_read_obs_netcdf4ahi_jaxa.inc
  var/da/da_radiance/da_setup_radiance_structures.inc
  var/da/da_radiance/mod_clddet_geoir.f90
Labels: Develop Branch, New Feature, WRFDA
