Repository wrf-model/WRF, pull requests merged in 2020-12, with the labels that each got.

#1322 Updates to icloud3
  phys/module_radiation_driver.F
Labels: Develop Branch, PHYSICS

#1332 Update check_a_mundo to make FARMS work correctly
  share/module_check_a_mundo.F
Labels: bug, release-v4.2.2

#1328 Fix to saturation vapor pressure at low temperatures
  phys/module_mp_morr_two_moment.F
  phys/module_mp_morr_two_moment_aero.F
Labels: PHYSICS, bug, release-v4.2.2

#1315 Irrigation fixes on time constrains across different years and different local midnight hour
  phys/module_irrigation.F
Labels: PHYSICS, bug, release-v4.2.2

#1313 Sea ice fix
  phys/module_surface_driver.F
Labels: PHYSICS, bug, release-v4.2.2

#1259 additional factor when converting surface heat fluxes from dry to moist theta
  dyn_em/module_diffusion_em.F
Labels: Dynamics ARW, bug, release-v4.2.2

#1304 km_opt=5 causes several divide by 0
  dyn_em/module_diffusion_em.F
Labels: Dynamics ARW, PHYSICS, bug, release-v4.2.2

#1317 Rrtmk fix
  phys/module_ra_rrtmg_swk.F
  phys/module_radiation_driver.F
Labels: bug, release-v4.2.2

#1307 use tke_seed_value only when necessary
  dyn_em/module_diffusion_em.F
  wrftladj/module_diffusion_em_ad.F
  wrftladj/module_diffusion_em_tl.F
Labels: PHYSICS, bug, release-v4.2.2

#1301 1st gfortran stanza target for raspberry pi (add aarch64 and armv7l)
  arch/configure.defaults
Labels: release-v4.2.2

#1327 bug fix: improper indexing in add aircraft emissions
  chem/module_emissions_anthropogenics.F
Labels: WRF Chem, bug, release-v4.2.2
