Repository wrf-model/WRF, pull requests merged in 2020-07, with the labels that each got.

#1225 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: release-v4.2.1

#1222 bug fix for VarBC when num_fgat_time > 1
  var/da/da_minimisation/da_get_innov_vector.inc
  var/da/da_minimisation/da_minimisation.f90
  var/da/da_radiance/da_get_innov_vector_radiance.inc
Labels: WRFDA, bug, release-v4.2.1

#1183 Replace "derf()" with standard "erf()" in SBM MP scheme
  phys/module_mp_SBM_polar_radar.F
Labels: PHYSICS, bug, release-v4.2.1

#1190 Filling aerssa2d/aerasy2d if sw = 5 and prescribed values from namelist
  phys/module_ra_aerosol.F
Labels: PHYSICS, bug, release-v4.2.1

#1208 Fix occurrence of time for max/min of diagnostics in clWRF
  phys/module_diag_cl.F
Labels: bug, release-v4.2.1

#1213 Fix INTEGER interpolation and feedback Registry arguments
  Registry/Registry.EM_COMMON
  Registry/registry.clm
  Registry/registry.noahmp
Labels: bug, release-v4.2.1

#1219 fixed divide by zero in Shin-Hong PBL
  phys/module_bl_shinhong.F
Labels: PHYSICS, bug, release-v4.2.1

#1221 Remove nonstandard spacing in macro as workaround for LLVM bug
  phys/module_mp_fast_sbm.F
Labels: PHYSICS, bug, release-v4.2.1

#1223 Release v4.2.1 Fire compile error
  phys/module_fr_fire_phys.F
Labels: PHYSICS, bug, release-v4.2.1

#1228 solar diag time series segfault - package needs variables
  Registry/Registry.EM_COMMON
Labels: PHYSICS, bug, release-v4.2.1

#1235 Bug fix advection TKE generated by wind farms
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  phys/module_pbl_driver.F
  phys/module_wind_fitch.F
  run/README.namelist
Labels: PHYSICS, bug, release-v4.2.1

#1247 Fix 1d advection testing program, broken with hybrid vert coord
  dyn_em/module_advect_em.F
Labels: bug, release-v4.2.1

#1217 enhanced slope calculation at domain boundary for periodic BC
  dyn_em/start_em.F
Labels: Dynamics ARW, bug, release-v4.2.1

#1255 Update PR commit message templates
  .github/PULL_REQUEST_TEMPLATE
  tools/commit_form.txt
Labels: Comments Only, release-v4.2.1

#1216 NSSL Microphysics log(0) FPE
  phys/module_mp_nssl_2mom.F
Labels: PHYSICS, bug, release-v4.2.1

#1248 Update README.grid_fdda - add (max_dom) for rinblw
  test/em_real/README.grid_fdda
  test/em_real/examples.namelist
Labels: bug, release-v4.2.1

#1243 Disable TUV diagnostics unless debugging
  chem/rxn.F
Labels: WRF Chem, bug, release-v4.2.1

#1214 bug fix for m_opt: fixed units of surface momentum flux
  dyn_em/module_diffusion_em.F
Labels: Dynamics ARW, bug, release-v4.2.1

#1257 Radiative heat tendency bug fix for RRTMK scheme
  phys/module_ra_rrtmg_swk.F
Labels: PHYSICS, bug, release-v4.2.1

#1253 Various syntax fixes found by FPT tool (static Fortran analysis mode)
  dyn_em/module_first_rk_step_part1.F
  external/io_grib2/bacio-1.3/baciof.F
  frame/Makefile
  phys/module_bl_mynn.F
Labels: bug, release-v4.2.1

#1261 Update version to v4.2.1
  README
  inc/version_decl
Labels: release-v4.2.1
