Repository wrf-model/WRF, pull requests merged in 2020-10, with the labels that each got.

#1294 Chem: Prevent seg fault due to numgas==0
  chem/chemics_init.F
Labels: WRF Chem, bug, release-v4.2.2

#1277 Bug fixes in deng shallow cumulus parameterization
  phys/module_shcu_deng.F
Labels: PHYSICS, bug, release-v4.2.2

#1280 Fix vertical indices of c1h and c2h in ideal case init of ph_1
  dyn_em/module_initialize_ideal.F
Labels: bug, release-v4.2.2

#1283 fixes irrigation channel: water not passed to the lsm
  phys/module_surface_driver.F
Labels: bug, release-v4.2.2

#1295 Background effective radius consistency fix
  phys/module_mp_thompson.F
  phys/module_mp_wdm5.F
  phys/module_mp_wdm6.F
  phys/module_mp_wdm7.F
  phys/module_mp_wsm3.F
  phys/module_mp_wsm5.F
  phys/module_mp_wsm6.F
  phys/module_mp_wsm7.F
  phys/module_physics_init.F
  phys/module_ra_farms.F
  phys/module_radiation_driver.F
  share/module_model_constants.F
Labels: PHYSICS, bug, release-v4.2.2

#1299 Fix MPI synchronization in real
  external/RSL_LITE/module_dm.F
Labels: bug, release-v4.2.2

#1302 Fix horizontal advection flag usage when "mom" != "sca"
  dyn_em/module_first_rk_step_part1.F
  dyn_em/module_first_rk_step_part2.F
  dyn_em/solve_em.F
Labels: bug, release-v4.2.2

#1251 Temporary fix for gfortran/10 compiler complaints
  Makefile
  arch/configure.defaults
  configure
Labels: DAVE, bug, release-v4.2.2

#1286 Fixes occasional instabilities in the surface layer option 1
  phys/module_sf_sfclayrev.F
Labels: PHYSICS, bug, release-v4.2.2

#1256 Enhancement for crop-specific parameters in Noah-MP-Crop
  phys/module_sf_noahmpdrv.F
  phys/module_sf_noahmplsm.F
  run/MPTABLE.TBL
Labels: PHYSICS, bug, release-v4.2.2

#1300 Inconsistent arg types (integer kind) across subroutine call
  external/io_int/module_io_int_read.F90
Labels: bug, release-v4.2.2
