Repository wrf-model/WRF, pull requests merged in 2020-01, with the labels that each got.

#1051 Fix comments in hybrid coordinate registry
  Registry/registry.hyb_coord
Labels: bug, release-v4.1.4

#1049 HWRF fixes: build = replicated symbol; run = link in look-up tables
  Makefile
  external/RSL_LITE/module_dm.F
Labels: bug, release-v4.1.4

#1038 Remove pop/push communicator on non MPI runs
  external/RSL_LITE/module_dm.F
Labels: bug, release-v4.1.4

#1033 Increase max_eta from 1001 to 10001
  dyn_em/module_initialize_real.F
  frame/module_driver_constants.F
Labels: bug, release-v4.1.4

#1035 add description for LANDUSE variables
  phys/module_physics_init.F
Labels: Comments Only, Develop Branch, PHYSICS, release-v4.2

#1054 Coarse-grid DX, DY compute all other domain grid distances
  share/module_check_a_mundo.F
  test/em_b_wave/namelist.input
  test/em_b_wave/namelist.input.backwards
  test/em_esmf_exp/namelist.input.jan00.ESMFSST
  test/em_esmf_exp/namelist.input.jan00.NETCDFSST
  test/em_fire/namelist.input_hill_simple
  test/em_fire/namelist.input_two_fires
  test/em_heldsuarez/namelist.input
  test/em_les/namelist.input
  test/em_les/namelist.input.SGP
  test/em_les/namelist.input_shalconv
  test/em_quarter_ss/namelist.input
  test/em_quarter_ss/namelist.input_2to1
  test/em_quarter_ss/namelist.input_3to1
  test/em_quarter_ss/namelist.input_4to1
  test/em_quarter_ss/namelist.input_5to1
  test/em_real/namelist.input
  test/em_real/namelist.input.4km
  test/em_real/namelist.input.chem
  test/em_real/namelist.input.diags
  test/em_real/namelist.input.global
  test/em_real/namelist.input.jan00
  test/em_real/namelist.input.jun01
  test/em_real/namelist.input.ndown_1
  test/em_real/namelist.input.ndown_2
  test/em_real/namelist.input.ndown_3
  test/em_real/namelist.input.pbl-les
  test/em_real/namelist.input.volc
Labels: Develop Branch, New Feature, release-v4.2

#1026 Fixing the problem that km_opt=5 breaks km_opt=2 and cleaning codes
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  dyn_em/module_diffusion_em.F
  dyn_em/module_first_rk_step_part2.F
  dyn_em/solve_em.F
  share/module_check_a_mundo.F
Labels: Develop Branch, New Feature, PHYSICS, release-v4.2

#990 Multiple LBC files for ARW, run-time option
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  main/real_em.F
  run/README.namelist
  share/mediation_integrate.F
  share/module_check_a_mundo.F
  test/em_real/examples.namelist
Labels: Develop Branch, Enhancement, release-v4.2

#981 Fix to allow RRTMG longwave radiation (ra_lw_physics=4) to be used with vertical nesting
  phys/module_radiation_driver.F
  share/module_check_a_mundo.F
Labels: Develop Branch, PHYSICS, release-v4.2

#965 Thompson MP: new one-moment Graupel y-intercept
  phys/module_diag_misc.F
  phys/module_mp_thompson.F
Labels: Develop Branch, PHYSICS, release-v4.2

#1063 Update to MYNN-EDMF
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_bl_mynn.F
  phys/module_pbl_driver.F
  phys/module_physics_init.F
  share/module_check_a_mundo.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#1055 Allow > 9999 MPI processes
  arch/configure.defaults
  external/RSL_LITE/c_code.c
  external/RSL_LITE/module_dm.F
  external/RSL_LITE/rsl_lite.h
Labels: Develop Branch, Enhancement, release-v4.2

#1059 Add year dependent CO2 function as default for RRTMG only
  phys/module_ra_rrtmg_lw.F
  phys/module_ra_rrtmg_lwf.F
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
  phys/module_radiation_driver.F
Labels: Develop Branch, Enhancement, PHYSICS, release-v4.2

#1043 Fix for Deng shallow combined with other subgrid cloud options
  phys/module_radiation_driver.F
Labels: bug, release-v4.1.4

#1066 Enabling WRF build with ESMF library
  external/esmf_time_f90/ESMF_Alarm.F90
  external/esmf_time_f90/ESMF_AlarmClock.F90
  external/esmf_time_f90/ESMF_Base.F90
  external/esmf_time_f90/ESMF_BaseTime.F90
  external/esmf_time_f90/ESMF_Calendar.F90
  external/esmf_time_f90/ESMF_Clock.F90
  external/esmf_time_f90/ESMF_Mod.F90
  external/esmf_time_f90/ESMF_Stubs.F90
  external/esmf_time_f90/ESMF_Time.F90
  external/esmf_time_f90/ESMF_TimeInterval.F90
  external/esmf_time_f90/Meat.F90
Labels: Develop Branch, Enhancement, release-v4.2
