Repository wrf-model/WRF, pull requests merged in 2021-11, with the labels that each got.

#1575 WRFDA for racm_soa_vbs_da (chem_opt=108) in the WRF-Chem model
  Registry/registry.var_chem
  var/da/da_chem_sfc/da_ao_stats_chem_sfc.inc
  var/da/da_chem_sfc/da_calculate_grady_chem_sfc.inc
  var/da/da_chem_sfc/da_chem_sfc.f90
  var/da/da_chem_sfc/da_get_innov_vector_chem_sfc.inc
  var/da/da_chem_sfc/da_residual_chem_sfc.inc
  var/da/da_chem_sfc/da_transform_xtoy_chem_sfc.inc
  var/da/da_chem_sfc/da_transform_xtoy_chem_sfc_adj.inc
  var/da/da_define_structures/da_allocate_observations_chem_sfc.inc
  var/da/da_define_structures/da_deallocate_background_errors.inc
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_main/da_update_firstguess.inc
  var/da/da_obs_io/da_final_write_obs_gas_sfc.inc
  var/da/da_obs_io/da_read_obs_chem_sfc.inc
  var/da/da_obs_io/da_read_omb_tmp.inc
  var/da/da_obs_io/da_scan_obs_chem_sfc.inc
  var/da/da_obs_io/da_write_obs_chem_sfc.inc
  var/da/da_setup_structures/da_get_vertical_truncation.inc
  var/da/da_setup_structures/da_setup_background_errors.inc
  var/da/da_setup_structures/da_setup_be_regional.inc
  var/da/da_setup_structures/da_setup_firstguess_wrf.inc
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_obs_structures_chem_sfc.inc
  var/da/da_statistics/da_analysis_stats.inc
  var/da/da_statistics/da_print_qcstat.inc
  var/da/da_transfer_model/da_transfer_model.f90
  var/da/da_transfer_model/da_transfer_xatoanalysis.inc
  var/da/da_vtox_transforms/da_transform_vchemtox_adj.inc
Labels: bug, WRFDA, WRF Chem, New Feature, Develop Branch

#1585 New Capability of GPM GMI Radiance Data Assimilation
  Registry/registry.var
  var/build/depend.txt
  var/da/da_radiance/da_allocate_rad_iv.inc
  var/da/da_radiance/da_deallocate_radiance.inc
  var/da/da_radiance/da_initialize_rad_iv.inc
  var/da/da_radiance/da_qc_gmi.inc
  var/da/da_radiance/da_qc_rad.inc
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_radiance1.f90
  var/da/da_radiance/da_radiance_init.inc
  var/da/da_radiance/da_read_obs_hdf5gmi.inc
  var/da/da_radiance/da_setup_radiance_structures.inc
  var/da/da_radiance/module_radiance.f90
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_structures.f90
  var/run/VARBC.in
  var/run/radiance_info/gpm-1-gmi.info
Labels: WRFDA, Develop Branch

#1577 Syntax errors in physics routines: *- and *+
  phys/module_mp_nssl_2mom.F
  phys/module_mp_ntu.F
  phys/module_sf_noahmplsm.F
Labels: bug, PHYSICS, release-v4.3.2

#1516 bug fix: initialization of 1000-h fuel moisture content, computation of the net fuel load
  phys/module_fr_fire_phys.F
Labels: bug, WRF Fire, release-v4.3.2

#1588 Fix misspelling in comment: pressure
  share/mediation_integrate.F
  share/mediation_nest_move.F
Labels: Comments Only, release-v4.3.2

#1580 smooth_cg_topo=T requires soil elevation data
  dyn_em/module_initialize_real.F
Labels: bug, release-v4.3.2

#1576 configure script missing quotes in two echo statements
  configure
Labels: bug, release-v4.3.2

#1574 Remove photolysis rates from default history stream
  Registry/registry.chem
Labels: WRF Chem, release-v4.3.2

#1573 Fix description for dustload5
  Registry/registry.chem
Labels: WRF Chem, Comments Only, release-v4.3.2

#1589 Correct output variable name for CLM packaging
  Registry/Registry.EM_COMMON
Labels: release-v4.3.2
