Repository wrf-model/WRF, pull requests merged in 2021-02, with the labels that each got.

#1368 Bug fix: Adding `chem_opt = 202` to `n2o5_hetchem` conditional
  chem/chemics_init.F
Labels: Develop Branch, WRF Chem, bug

#1358 Chem: Wet scavenging optional for MP schemes
  Registry/registry.chem
  chem/chem_driver.F
  dyn_em/solve_em.F
  phys/module_microphysics_driver.F
  phys/module_mp_morr_two_moment.F
  phys/module_mp_morr_two_moment_aero.F
  phys/module_mp_nssl_2mom.F
  phys/module_mp_thompson.F
  phys/module_mp_wsm6.F
  share/module_trajectory.F
Labels: Develop Branch, New Feature, WRF Chem

#1342 Add pH diagnostics for mozart_mosaic_4bin_aq chemistry
  Registry/registry.chem
  chem/aerosol_driver.F
  chem/chem_driver.F
  chem/cloudchem_driver.F
  chem/module_chem_cup.F
  chem/module_mosaic_cloudchem.F
  chem/module_mosaic_driver.F
  chem/module_mosaic_therm.F
Labels: Develop Branch, New Feature, WRF Chem

#1353 Remove UM trajectory initialization from real
  dyn_em/module_initialize_real.F
Labels: Develop Branch, bug

#1391 height-level diagnostic fixes: add p_zl, use ln(p) interp for pressure
  Registry/registry.diags
  dyn_em/start_em.F
  phys/module_diag_zld.F
  phys/module_diagnostics_driver.F
Labels: Develop Branch, Enhancement

#1395 add HLC.TBL and wind-turbine-1.tbl to clean list
  clean
Labels: Develop Branch

#1306 update namelist.input to current recommendations and newer case
  test/em_real/namelist.input
  test/em_real/namelist.input.default
Labels: Develop Branch

#1389 Alter graupel Y-intercept parameter diagnosis (replacement of PR#1324)
  phys/module_diag_nwp.F
  phys/module_mp_thompson.F
Labels: Develop Branch, Enhancement, PHYSICS

#1393 Remove unused i1 array rho phy
  Registry/Registry.EM_COMMON
  Registry/registry.wrfplus
  dyn_em/module_after_all_rk_steps.F
  dyn_em/solve_em.F
  phys/module_diag_afwa.F
  phys/module_diagnostics_driver.F
  wrftladj/solve_em_ad.F
  wrftladj/solve_em_tl.F
Labels: Develop Branch

#1387 Bug fix in Deng shcu parameterization for updraft top calculation
  phys/module_shcu_deng.F
Labels: Develop Branch, Infrastructure: OK, PHYSICS, bug

#1398 Fix for instances of dt = 0 when using adaptive time stepping
  dyn_em/adapt_timestep_em.F
Labels: Develop Branch, Infrastructure: OK, bug

#1394 Bug fix in FARMS parameterization for ice cloud optical thickness calculation
  phys/module_ra_farms.F
Labels: Develop Branch, Infrastructure: OK, PHYSICS, bug

#1399 Add git hash and a summary of files changed
  chem/chemics_init.F
  chem/convert_emiss.F
  clean
  compile
  inc/.gitignore
  main/ideal_em.F
  main/ideal_nmm.F
  main/module_wrf_top.F
  main/ndown_em.F
  main/real_em.F
  main/real_nmm.F
  main/tc_em.F
  share/input_wrf.F
Labels: Develop Branch, Enhancement, Infrastructure: OK

#1354 Chem: Adding two improvements related to convective transport of trace gases
  chem/Makefile
  chem/chem_driver.F
  chem/chemics_init.F
  chem/depend.chem
  chem/module_ctrans_grell.F
  chem/module_input_chem_data.F
  dyn_em/module_first_rk_step_part1.F
  phys/Makefile
  phys/module_cu_gf_ctrans.F
  phys/module_cu_gf_deep.F
  phys/module_cu_gf_sh.F
  phys/module_cu_gf_wrfdrv.F
  phys/module_cumulus_driver.F
  share/Makefile
  share/module_HLaw.F
  share/module_chem_share.F
  share/module_ctrans_aqchem.F
Labels: Develop Branch, New Feature, WRF Chem

#1388 Possibility to insert initial clouds into cold-start
  Registry/Registry.EM_COMMON
  dyn_em/depend.dyn_em
  dyn_em/module_initialize_real.F
  run/README.namelist
Labels: Develop Branch, Infrastructure: OK, New Feature, PHYSICS

#1409 Created README.physics_files to describe dependencies with linked files
  Makefile
  clean
  run/README.physics_files
Labels: Comments Only, Develop Branch, PHYSICS

#1372 Add dynamic irrigation management practices to Noah-MP
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.noahmp
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/module_PHYSICS_CALLS.F
  dyn_nmm/start_domain_nmm.F
  phys/module_physics_init.F
  phys/module_sf_noahmpdrv.F
  phys/module_sf_noahmplsm.F
  phys/module_surface_driver.F
  run/MPTABLE.TBL
  run/README.namelist
  share/output_wrf.F
Labels: Develop Branch, Infrastructure: OK, New Feature, PHYSICS

#1403 Noah mp snow
  phys/module_sf_noahmpdrv.F
  phys/module_sf_noahmplsm.F
  run/MPTABLE.TBL
Labels: Develop Branch, Enhancement, PHYSICS

#1405 Add Noah-MP output variable QRAINXY
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.noahmp
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/module_PHYSICS_CALLS.F
  dyn_nmm/start_domain_nmm.F
  phys/module_physics_init.F
  phys/module_sf_noahmpdrv.F
  phys/module_sf_noahmplsm.F
  phys/module_surface_driver.F
  wrftladj/module_physics_init_ad.F
  wrftladj/module_physics_init_tl.F
  wrftladj/start_em_ad.F
  wrftladj/start_em_tl.F
Labels: Develop Branch, Enhancement, Infrastructure: OK, PHYSICS

#1408 Fix to allow use_theta_m=1 with vertical nesting and simplify rebalance options
  Registry/Registry.EM_COMMON
  dyn_em/module_initialize_real.F
  dyn_em/start_em.F
  external/RSL_LITE/module_dm.F
  share/module_check_a_mundo.F
Labels: Develop Branch, Dynamics ARW, Infrastructure: OK, bug

#1364 NTU microphysics scheme
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.var
  Registry/registry.wrfplus
  dyn_em/solve_em.F
  dyn_em/start_em.F
  phys/Makefile
  phys/module_microphysics_driver.F
  phys/module_mp_ntu.F
  phys/module_physics_init.F
  run/README.namelist
  share/module_bc.F
  wrftladj/module_bc_ad.F
  wrftladj/module_bc_tl.F
  wrftladj/module_microphysics_driver_ad.F
  wrftladj/module_microphysics_driver_tl.F
  wrftladj/solve_em_ad.F
  wrftladj/solve_em_tl.F
Labels: 15-km Testing: OK, Develop Branch, Infrastructure: OK, New Feature, PHYSICS

#1285 Add Montornes's solar eclipse modelling
  Makefile
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  clean
  dyn_em/module_first_rk_step_part1.F
  dyn_nmm/module_PHYSICS_CALLS.F
  phys/Makefile
  phys/module_ra_eclipse.F
  phys/module_ra_goddard.F
  phys/module_ra_gsfcsw.F
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_sw.F
  phys/module_radiation_driver.F
  run/README.namelist
  run/eclipse_besselian_elements.dat
  share/module_check_a_mundo.F
Labels: Develop Branch, Infrastructure: OK, New Feature, PHYSICS

#1258 Clear sky 3D radiative heat tendencies added as output variables with CAM and all RRTMG radiation schemes
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  dyn_nmm/module_PHYSICS_CALLS.F
  phys/module_ra_cam.F
  phys/module_ra_rrtm.F
  phys/module_ra_rrtmg_lw.F
  phys/module_ra_rrtmg_lwf.F
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
  phys/module_ra_rrtmg_swk.F
  phys/module_radiation_driver.F
Labels: Develop Branch, Infrastructure: OK, PHYSICS

#1396 Bug fix to use correct rho value in cal_titau subroutines
  Registry/Registry.EM_COMMON
  dyn_em/module_diffusion_em.F
  dyn_em/solve_em.F
Labels: Develop Branch, Dynamics ARW, Infrastructure: OK, bug

#1338 Avoid double staggering of ww in vertical advection of geopotential
  Registry/Registry.EM_COMMON
  dyn_em/module_big_step_utilities_em.F
  dyn_em/module_small_step_em.F
  run/README.namelist
Labels: Develop Branch, Dynamics ARW, Infrastructure: OK, New Feature

#1305 Add multilayer UCMs to YSU PBL parameterization
  phys/module_bl_ysu.F
  phys/module_pbl_driver.F
  phys/module_physics_init.F
  run/README.namelist
Labels: 15-km Testing: OK, Develop Branch, Infrastructure: OK, New Feature, PHYSICS

#1415 Remove necessity to run 'run_me_first' scripts for ideal cases
  Makefile
  test/em_b_wave/run_me_first.csh
  test/em_convrad/run_me_first.csh
  test/em_quarter_ss/run_me_first.csh
  test/em_scm_xy/run_me_first.csh
  test/em_seabreeze2d_x/run_me_first.csh
  test/em_tropical_cyclone/run_me_first.csh
Labels: Develop Branch, Enhancement, PHYSICS

#1401 Change default fractional_seaice option from 0 to 1
  Registry/Registry.EM_COMMON
  phys/module_surface_driver.F
Labels: Develop Branch, Infrastructure: OK, PHYSICS

#1303 Add a new E-epsilon PBL scheme:
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  phys/Makefile
  phys/module_bl_eepsilon.F
  phys/module_pbl_driver.F
  phys/module_physics_addtendc.F
  phys/module_physics_init.F
  run/README.namelist
Labels: 15-km Testing: OK, Develop Branch, Infrastructure: OK, New Feature, PHYSICS

#1329 Add the NOAA/GSL enhanced orographic drag suite used in the RAP/HRRR NWP model.
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  main/depend.common
  phys/Makefile
  phys/module_bl_gwdo_gsl.F
  phys/module_pbl_driver.F
  run/README.namelist
  share/module_check_a_mundo.F
Labels: Develop Branch, Infrastructure: OK, New Feature, PHYSICS
