Repository wrf-model/WRF, pull requests merged in 2021-05, with the labels that each got.

#1501 Remove ARW nesting "us" (feedback and smoothing) from all GWD variables
  Registry/Registry.EM_COMMON
Labels: Dynamics ARW, bug, release-v4.3

#1502 Add all smoothed fields to FEEDBACK HALO
  Registry/Registry.EM_COMMON
Labels: Dynamics ARW, bug, release-v4.3

#1503 Ensure URBPARM_LCZ.TBL is linked to em_* directory & error msg correct
  Makefile
  clean
  phys/module_sf_urban.F
Labels: Enhancement, bug, release-v4.3

#1508 Update README.physics_files for new files since V4.2, and update chem_opt settings
  run/README.physics_files
Labels: README, release-v4.3

#1492 fix irrigation schedule
  phys/module_irrigation.F
Labels: PHYSICS, bug, release-v4.3

#1510 Revert w_crit_cfl back to 1.0 (from temporary 1.2)
  Registry/Registry.EM_COMMON
Labels: Dynamics ARW, bug, release-v4.3

#1512 http -> https for README.md
  README.md
Labels: Comments Only, bug, release-v4.3

#1511 Updated top-level README for V4.3 release
  README
Labels: Comments Only, release-v4.3

#1513 Consistency updates to namelist.input
  test/em_real/namelist.input
Labels: Comments Only, release-v4.3

#1519 improve MAD-WRF section
  run/README.namelist
Labels: Comments Only, release-v4.3.1

#1517 got_var_sso needs to be in history file for DA
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.3.1
