Repository wrf-model/WRF, pull requests merged in 2021-03, with the labels that each got.

#1422 Fix for fractional_seaice option, again
  phys/module_surface_driver.F
Labels: bug

#1424 Remove temporary file from test/em_real
  test/em_real/landFilenames
Labels: Comments Only, Develop Branch

#1423 Thompson MP: reduce fake aerosol emissions by 4x
  phys/module_mp_thompson.F
Labels: Develop Branch, PHYSICS, bug

#1417 Adding the MAD-WRF model
  Registry/Registry.EM
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/Registry.tladj
  Registry/registry.chem
  doc/README.madwrf
  dyn_em/depend.dyn_em
  dyn_em/module_big_step_utilities_em.F
  dyn_em/module_initialize_real.F
  dyn_em/solve_em.F
  main/depend.common
  phys/Makefile
  phys/module_madwrf.F
  phys/module_microphysics_driver.F
  phys/module_physics_init.F
  run/README.namelist
  share/module_check_a_mundo.F
  share/module_optional_input.F
Labels: Develop Branch, New Feature, PHYSICS

#1425 Develop new CLM / MEGANv2.1 interface
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.chem
  Registry/registry.clm
  Registry/registry.dimspec
  chem/KPP/mechanisms/saprc99/saprc99.eqn
  chem/KPP/mechanisms/saprc99/saprc99.spc
  chem/chem_driver.F
  chem/chemics_init.F
  chem/emissions_driver.F
  chem/module_dep_simple.F
  chem/module_emissions_anthropogenics.F
  chem/module_ftuv_driver.F
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/module_PHYSICS_CALLS.F
  frame/module_driver_constants.F
  phys/module_physics_init.F
  phys/module_sf_clm.F
  phys/module_surface_driver.F
  share/module_check_a_mundo.F
Labels: Develop Branch, New Feature, WRF Chem

#1427 urban updates: solar panel, green roof, building drag coefficient
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  Registry/registry.dimspec
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  dyn_nmm/module_PHYSICS_CALLS.F
  dyn_nmm/start_domain_nmm.F
  phys/module_physics_init.F
  phys/module_sf_bem.F
  phys/module_sf_bep_bem.F
  phys/module_sf_noahdrv.F
  phys/module_sf_noahmpdrv.F
  phys/module_sf_urban.F
  phys/module_surface_driver.F
  run/URBPARM.TBL
  run/URBPARM_LCZ.TBL
  share/module_check_a_mundo.F
Labels: Develop Branch, New Feature, PHYSICS

#1355 Modifications to improve WRF-CTSM coupling
  phys/module_surface_driver.F
  share/module_soil_pre.F
Labels: Develop Branch, Infrastructure: OK, PHYSICS

#1438 Add new options to readme
  run/README.namelist
Labels: Comments Only, Develop Branch

#1439 Removed 'max_rot_angle_gwd' from Registry - no longer used.
  Registry/Registry.EM_COMMON
Labels: Develop Branch

#1436 Bug fix: RRTMG SW solar source function calculation
  phys/module_ra_rrtmg_sw.F
Labels: Develop Branch, PHYSICS, bug

#1435 Fix to enable vertical nesting with hybrid vertical coordinate
  external/RSL_LITE/module_dm.F
  share/module_check_a_mundo.F
Labels: Develop Branch, Dynamics ARW, bug

#1430 Bug fix in buoyancy diagnostic function
  phys/module_diag_functions.F
Labels: Develop Branch, PHYSICS, bug

#1373 Implicit Explicit Vertical Advection (IEVA)
  Registry/Registry.EM_COMMON
  dyn_em/Makefile
  dyn_em/module_advect_em.F
  dyn_em/module_big_step_utilities_em.F
  dyn_em/module_em.F
  dyn_em/module_ieva_em.F
  dyn_em/solve_em.F
  run/README.namelist
  test/em_real/namelist.input.IEVA.4km
Labels: Develop Branch, Dynamics ARW, New Feature

#1434 bug fix: initialize lat/lon with zeros only for nested fire runs
  dyn_em/module_initialize_fire.F
  phys/module_fr_fire_util.F
Labels: WRF Fire, bug

#1431 removing dxy from GOCART dust emission schemes. Code clean-up.
  Registry/registry.chem
  chem/emissions_driver.F
  chem/module_gocart_dust.F
  chem/module_gocart_dust_afwa.F
  chem/module_qf03.F
  chem/module_uoc_dust.F
Labels: Enhancement, WRF Chem

#1442 Fix bit for bit error in OpenMP IEVA
  dyn_em/module_big_step_utilities_em.F
Labels: Develop Branch, Dynamics ARW, bug

#1443 Memory-sized arrays changed to tile-sized arrays
  dyn_em/module_ieva_em.F
Labels: Develop Branch, PHYSICS, bug

#1433 US EPA ACM2 and PX LSM updates Mar 2021
  phys/module_bl_acm.F
  phys/module_pbl_driver.F
  phys/module_sf_pxlsm.F
  phys/module_sf_pxsfclay.F
Labels: Develop Branch, New Feature, PHYSICS, bug

#1441 Corrections for ntu_init
  dyn_em/start_em.F
  phys/module_mp_ntu.F
  phys/module_physics_init.F
Labels: Develop Branch, bug

#1446 Remove ASCII chars outside of 32-127 range
  chem/chemics_init.F
  chem/module_mosaic_newnucb.F
  hydro/Routing/module_gw_gw2d.F
  phys/module_fr_fire_phys.F
  phys/module_gocart_coupling.F
  phys/module_mp_fast_sbm.F
  phys/module_mp_gsfcgce_4ice_nuwrf.F
  phys/module_mp_ntu.F
  phys/module_ra_eclipse.F
  phys/module_sf_bep_bem.F
  phys/module_sf_noahmplsm.F
  share/module_check_a_mundo.F
  tools/non_ascii_finder.F
Labels: Comments Only, Develop Branch, bug

#1450 P3: update offline generation code for lookup tables
  run/create_p3_lookupTable_1.f90
  run/create_p3_lookupTable_1.f90-v5.1.6_b01
  run/create_p3_lookupTable_2.f90-v4.1
Labels: Comments Only, PHYSICS, release-v4.3

#1451 update version_decl to v4.3
  inc/version_decl
Labels: release-v4.3
