Repository wrf-model/WRF, pull requests merged in 2021-01, with the labels that each got.

#1337 Update vertical interpolation stand-alone, fix vert_interp call
  dyn_em/module_initialize_real.F
Labels: bug, release-v4.2.2

#1352 km_opt=5 heat flux fix should just use lowest level qv
  dyn_em/module_diffusion_em.F
Labels: bug, release-v4.2.2

#1339 Fix return type on wrf_dm_max_int (should be an integer)
  external/RSL_LITE/module_dm.F
Labels: bug, release-v4.2.2

#1340 Fix examples.namelist namelist record name: domains
  test/em_real/examples.namelist
Labels: bug, release-v4.2.2

#1326 Add missing compiler name for Intel HSB/BDW config
  arch/configure.defaults
Labels: bug, release-v4.2.2

#1273 Remove obsolescent and non-standard features in physics modules
  phys/module_cu_mskf.F
  phys/module_cu_scalesas.F
  phys/module_dust_emis.F
  phys/module_mp_fast_sbm.F
  phys/module_mp_milbrandt2mom.F
  phys/module_mp_p3.F
  phys/module_mp_thompson.F
  phys/module_ra_goddard.F
  phys/module_shcu_deng.F
Labels: PHYSICS, bug, release-v4.2.2

#1284 Bug fixes related to solar diag package: COS(zenith angle), non-existent hydrometeors, shortwave irradiances in time series
  Registry/Registry.EM_COMMON
  Registry/registry.solar_fields
  phys/module_diag_solar.F
  phys/module_diagnostics_driver.F
  phys/module_radiation_driver.F
  run/README.tslist
  share/wrf_timeseries.F
Labels: PHYSICS, bug, release-v4.2.2

#1359 Corrected bug in mixactivate for diagnostic CCN in sectional schemes
  phys/module_mixactivate.F
Labels: PHYSICS, bug, release-v4.2.2

#1336 fixed boundary issues in rhs_ph
  dyn_em/module_big_step_utilities_em.F
Labels: Dynamics ARW, bug, release-v4.2.2

#1363 Fix for lh_urb2d diagnostics
  phys/module_sf_noahmpdrv.F
Labels: bug, release-v4.2.2

#1314 Corner points
  share/module_bc.F
Labels: Dynamics ARW, bug, release-v4.2.2
