Repository wrf-model/WRF, pull requests merged in 2021-04, with the labels that each got.

#1452 IEVA: change upper case string "CFL" to lower case
  dyn_em/module_big_step_utilities_em.F
Labels: release-v4.3

#1457 Fix for fractional seaice using MYJ and QNSE surface layer and MYNN PBL
  phys/module_surface_driver.F
Labels: PHYSICS, bug, release-v4.3

#1454 Fixed staggering of shallow cumulus tendencies of u and v at periodic boundaries
  Registry/Registry.EM_COMMON
Labels: PHYSICS, bug, release-v4.3

#1453 Boulac PBL tendency should not be added to previous value
  phys/module_bl_boulac.F
Labels: PHYSICS, bug, release-v4.3

#1455 WRF-urban minor bug fix & readme.namelist update for noahmp
  phys/module_sf_bep_bem.F
  run/README.namelist
Labels: PHYSICS, bug, release-v4.3

#1458 turn ysu_topdown_pblmix on by default
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
Labels: Enhancement, PHYSICS, release-v4.3

#1462 Added two missing END PARALLEL DO directives for do_avgflx_em=1
  dyn_em/solve_em.F
Labels: Dynamics ARW, bug, release-v4.3

#1463 Removed redundant code in vertical_diffusion_implicit
  dyn_em/module_diffusion_em.F
Labels: Dynamics ARW, bug, release-v4.3

#1456 Noah-MP Dynamic Irrigation Packaged 2d fields
  Registry/Registry.EM_COMMON
  Registry/Registry.NMM
  phys/module_sf_noahmplsm.F
Labels: PHYSICS, bug, release-v4.3

#1470 NML check: fractional seaice + SLAB not permitted
  Registry/Registry.EM_COMMON
  phys/module_surface_driver.F
  share/module_check_a_mundo.F
Labels: PHYSICS, bug, release-v4.3

#1464 Added NH3, CO2, CH4 fire emissions for RACM mechanisms.
  chem/module_add_emiss_burn.F
Labels: New Feature, WRF Chem, WRF Fire

#1475 Fixes for ieva option
  dyn_em/module_em.F
Labels: Dynamics ARW, bug, release-v4.3

#1472 Add Namelist Option 'reasonable_time_step_ratio' to README.namelist File
  run/README.namelist
Labels: release-v4.3

#1474 Remove un-used w_up array from MSKF scheme
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_cu_mskf.F
  phys/module_cumulus_driver.F
Labels: PHYSICS, bug, release-v4.3

#1473 Remove advance_clock call in ARW real main program
  main/real_em.F
Labels: bug, release-v4.3

#1478 Deng shcu - limit to prevent negative QV1D
  phys/module_shcu_deng.F
Labels: Enhancement, PHYSICS, bug, release-v4.3

#1479 Fix hybrid vertical coordinate 1d array assignment
  dyn_em/nest_init_utils.F
Labels: Dynamics ARW, bug, release-v4.3

#1487 Fix SFRV and LFRV names in Registry
  Registry/Registry.EM_COMMON
Labels: PHYSICS, bug, release-v4.3

#1481 NSSL Microphysics update (Release v4.3)
  phys/module_mp_nssl_2mom.F
  phys/module_physics_init.F
Labels: Enhancement, PHYSICS, release-v4.3

#1483 diffusion computed k-index == 0 for PBL
  dyn_em/module_diffusion_em.F
Labels: Dynamics ARW, bug, release-v4.3

#1485 Allow integer gridded fields in diffwrf
  external/io_netcdf/diffwrf.F90
Labels: Enhancement, release-v4.3

#1489 Package new vars from update of CLM scheme PR#1425
  Registry/Registry.EM_COMMON
Labels: Enhancement, PHYSICS, release-v4.3

#1488 Fix restart problem with 3 or more domains when o3input = 2
  Registry/Registry.EM_COMMON
Labels: bug, release-v4.3

#1484 Allow more run-time fields in namelist-controlled streams
  frame/module_domain.F
Labels: Enhancement, release-v4.3

#1495 corrected variable output names for max_msftx and max_msfty
  Registry/Registry.EM_COMMON
Labels: release-v4.3

#1490 Remove namelist spec_bdy_final_mu
  Registry/Registry.EM_COMMON
  dyn_em/solve_em.F
  run/README.namelist
  share/output_wrf.F
  wrftladj/solve_em_ad.F
  wrftladj/solve_em_tl.F
Labels: Dynamics ARW, release-v4.3

#1497 update README.gen_be_v3
  var/gen_be_v3/README.gen_be_v3
Labels: WRFDA, release-v4.3

#1486 Bug fix FARMS to use correct cloud transmittance
  phys/module_ra_farms.F
Labels: PHYSICS, bug, release-v4.3

#1494 Adding a check to avoid using shcu = 5 and icloud_bl
  share/module_check_a_mundo.F
Labels: bug, release-v4.3

#1498 Bugfix for the NoahMP dynamic irrigation scheme irrigation option (iopt_irr=2)
  phys/module_sf_noahmpdrv.F
Labels: PHYSICS, bug, release-v4.3
