Repository wrf-model/WRF, pull requests merged in 2021-12, with the labels that each got.

#1594 Another physics syntax error
  phys/module_mp_ntu.F
Labels: bug, release-v4.3.2

#1595 fix WRFDA CRTM Cray Fortran build
  var/external/crtm_2.3.0/libsrc/makefile
Labels: WRFDA, release-v4.3.2

#1557 Add new stanza for ARM aarch64/openmpi
  arch/configure.defaults
Labels: Enhancement, Infrastructure: OK, release-v4.3.2

#1596 PBL + LES restrictions
  Registry/Registry.EM_COMMON
  share/module_check_a_mundo.F
Labels: bug, PHYSICS, release-v4.3.2

#1598 Add time-varying greenhouse gases to RRTMG shortwave options
  main/depend.common
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
Labels: PHYSICS, Enhancement, Develop Branch

#1592 Bug fix for aerosol optics Mie extrapolation WRFchem
  chem/module_optical_averaging.F
Labels: WRF Chem, Develop Branch

#1583 Add calculation for accumulated physics tendencies for theta, qv, u and v
  Registry/Registry.EM_COMMON
  phys/module_diag_misc.F
  phys/module_diagnostics_driver.F
Labels: Develop Branch

#1601 build module_state_description.F -> force zero return code
  frame/Makefile
Labels: Enhancement, Develop Branch

#1600 Fix MPI synchronization in real.exe
  main/real_em.F
Labels: bug, Develop Branch

#1602 WRFDA gpsref code restructuring and diag fixes
  Registry/registry.var
  var/build/depend.txt
  var/da/da_control/da_control.f90
  var/da/da_gpsref/da_check_max_iv_gpsref.inc
  var/da/da_gpsref/da_get_innov_vector_gpsref.inc
  var/da/da_gpsref/da_get_innov_vector_gpsref_deprecated.inc
  var/da/da_gpsref/da_gpsref.f90
  var/da/da_gpsref/da_qc_gpsref.inc
  var/da/da_minimisation/da_get_innov_vector.inc
  var/da/da_obs_io/da_read_omb_tmp.inc
  var/da/da_obs_io/da_write_filtered_obs.inc
Labels: WRFDA, Develop Branch

#1591 Add RRTMG cloud overlap option 5
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_ra_rrtmg_lw.F
  phys/module_ra_rrtmg_sw.F
  phys/module_radiation_driver.F
  run/README.namelist
  share/output_wrf.F
Labels: PHYSICS, Develop Branch

#1590 Updates to MYNN surface layer scheme
  phys/module_sf_mynn.F
  phys/module_surface_driver.F
Labels: PHYSICS, Develop Branch

#1567 Removing legacy code and cleaning up logic for real processing of aerosol for mp_physics=28
  Registry/Registry.EM
  Registry/Registry.EM_CHEM
  Registry/Registry.EM_COMMON
  Registry/Registry.tladj
  Registry/registry.new3d_wif
  dyn_em/module_initialize_real.F
  share/module_check_a_mundo.F
  share/module_optional_input.F
Labels: PHYSICS, Develop Branch

#1603 a collection of WRFDA fixes related to ensdim_alpha use cases
  var/da/da_main/da_solve.inc
  var/da/da_minimisation/da_calculate_gradj.inc
  var/da/da_minimisation/da_calculate_j.inc
  var/da/da_minimisation/da_minimise_cg.inc
  var/da/da_minimisation/da_transform_vtod_wpec.inc
  var/da/da_minimisation/da_transform_vtod_wpec_adj.inc
  var/da/da_minimisation/da_transform_vtoy.inc
  var/da/da_minimisation/da_transform_vtoy_adj.inc
  var/da/da_setup_structures/da_setup_be_regional.inc
  var/da/da_vtox_transforms/da_transform_vpatox.inc
  var/da/da_vtox_transforms/da_transform_vpatox_adj.inc
  var/da/da_vtox_transforms/da_transform_vptox.inc
  var/da/da_vtox_transforms/da_transform_vptox_adj.inc
  var/da/da_vtox_transforms/da_transform_vtox.inc
  var/da/da_vtox_transforms/da_transform_vtox_adj.inc
  var/da/da_vtox_transforms/da_vtox_transforms.f90
Labels: WRFDA, Develop Branch

#1604 WRFDA memory usage reduction for thin_conv=true
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_obs_structures_ascii.inc
  var/da/da_setup_structures/da_setup_obs_structures_bufr.inc
  var/da/da_setup_structures/da_setup_structures.f90
Labels: WRFDA, Develop Branch

#1605 fix WRFDA stand-alone da_rad_diags.exe build with GNU Fortran 11
  var/da/da_monitor/da_rad_diags.f90
Labels: WRFDA, Develop Branch

#1607 update WRFDA radiance info to include metop-c-amsua and metop-c-mhs
  var/run/VARBC.in
  var/run/radiance_info/metop-3-amsua.info
  var/run/radiance_info/metop-3-mhs.info
Labels: WRFDA, Develop Branch

#1612 Put KIAPS rad LW back to original
  phys/module_ra_rrtmg_lwk.F
Labels: bug, PHYSICS, Develop Branch

#1613 WRFDA thin_conv code restructuring
  Registry/registry.var
  var/da/da_control/da_control.f90
  var/da/da_obs_io/da_obs_io.f90
  var/da/da_obs_io/da_read_obs_ascii.inc
  var/da/da_obs_io/da_read_obs_bufr.inc
  var/da/da_obs_io/da_scan_obs_ascii.inc
  var/da/da_radiance/da_setup_radiance_structures.inc
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_obs_structures_ascii.inc
  var/da/da_setup_structures/da_setup_obs_structures_bufr.inc
  var/da/da_setup_structures/da_setup_obs_structures_rain.inc
  var/da/da_setup_structures/da_setup_structures.f90
Labels: WRFDA, Develop Branch

#1610 Adding accumulated GHI and fixing registry units for solar diagnostics package
  Registry/Registry.EM_COMMON
  Registry/registry.solar_fields
  dyn_em/start_em.F
  phys/module_diag_solar.F
  phys/module_diagnostics_driver.F
  phys/module_physics_init.F
  run/README.tslist
  share/wrf_timeseries.F
Labels: bug, Develop Branch

#1617 add WRFDA satwnd.bufr ingest
  Registry/registry.var
  var/README.namelist
  var/build/depend.txt
  var/da/da_control/da_control.f90
  var/da/da_obs_io/da_obs_io.f90
  var/da/da_obs_io/da_read_obs_bufr.inc
  var/da/da_obs_io/da_read_obs_bufr_satwnd.inc
  var/da/da_radiance/gsi_thinning.f90
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_obs_structures_bufr.inc
  var/da/da_setup_structures/da_setup_structures.f90
Labels: WRFDA, Develop Branch
