Repository wrf-model/WRF, pull requests merged in 2022-03, with the labels that each got.

#1688 Bug fixes for pm10 assimilation with chem_opt=108
  var/da/da_chem_sfc/da_get_innov_vector_chem_sfc.inc
  var/da/da_obs_io/da_read_obs_chem_sfc.inc
Labels: WRFDA, release-v4.4

#1675 coszen made not optional in Dudhia swrad
  phys/module_ra_sw.F
Labels: bug, release-v4.4

#1681 resolve uninitialized variable issues in surface_driver
  phys/module_surface_driver.F
Labels: bug, release-v4.4

#1689 Urban model: fix undefined WDR and direction logic
  phys/module_sf_urban.F
Labels: bug, release-v4.4

#1692 Shin-Hong PBL fix for divide-by-zero problem
  phys/module_bl_shinhong.F
Labels: bug, release-v4.4

#1698 Shin-Hong PBL fix for divide-by-zero problem
  phys/module_bl_shinhong.F
Labels: bug, release-v4.4

#1700 Bug fix for emissivity in Noah urban code
  phys/module_sf_noahdrv.F
Labels: bug, release-v4.4

#1682 Add second no3 photolysis channel to TUV
  chem/KPP/mechanisms/mozart_mosaic_4bin/mozart_mosaic_4bin.tuv.jmap
  chem/KPP/mechanisms/mozart_mosaic_4bin_aq/mozart_mosaic_4bin_aq.tuv.jmap
  chem/KPP/mechanisms/mozcart/mozcart.tuv.jmap
  chem/KPP/mechanisms/t1_mozcart/t1_mozcart.tuv.jmap
Labels: bug, WRF Chem, release-v4.4

#1696 Fix wrong Ott lightning NOx distribution
  chem/module_lightning_nox_ott.F
Labels: bug, release-v4.4

#1614 adding custom eta levels to idealized fire runs
  dyn_em/module_initialize_fire.F
Labels: Enhancement, WRF Fire, release-v4.4
