Repository wrf-model/WRF, pull requests merged in 2022-04, with the labels that each got.

#1691 Refactoring of gocart dust emission in mosaic
  Registry/registry.chem
  chem/chem_driver.F
  chem/emissions_driver.F
  chem/module_gocart_drydep.F
  chem/module_gocart_dust_afwa.F
  chem/module_gocart_settling.F
  chem/module_mosaic_addemiss.F
Labels: Enhancement, release-v4.4

#1711 bug fix for WRF-urban rain input variable unit
  phys/module_sf_noahdrv.F
  phys/module_surface_driver.F
Labels: bug, release-v4.4

#1716 Make the print for submodule conditionally appearing in log file
  Makefile
Labels: bug, release-v4.4

#1704 Init Henry's Law Constants for MOZART & convective wet scavenging with GF
  main/depend.common
  phys/module_cu_gf_ctrans.F
Labels: bug, WRF Chem, PHYSICS, release-v4.4

#1718 Bug fix for chem DA omb/oma output
  var/da/da_obs_io/da_final_write_obs_gas_sfc.inc
  var/da/da_obs_io/da_read_omb_tmp.inc
  var/da/da_obs_io/da_write_obs_chem_sfc.inc
Labels: bug, WRFDA, release-v4.4

#1717 bug fix for Noah urban driver for longwave & shorwave input variables
  phys/module_sf_noahdrv.F
Labels: bug, release-v4.4

#1722 Reduce memory increase from PRs 1567 and 1616
  Registry/Registry.EM_COMMON
  Registry/registry.new3d_wif
Labels: bug, release-v4.4

#1715 Moving smoke aerosol emissions for Thompson AA scheme into separate module
  Registry/Registry.EM_COMMON
  phys/Makefile
  phys/module_fire_emis.F
  phys/module_microphysics_driver.F
  phys/module_mp_thompson.F
  share/module_check_a_mundo.F
  test/em_real/examples.namelist
Labels: Enhancement, release-v4.4

#1726 V4.4 bugfix gas omb
  var/da/da_chem_sfc/da_get_innov_vector_chem_sfc.inc
  var/da/da_chem_sfc/da_print_stats_chem_sfc.inc
  var/da/da_obs_io/da_read_obs_chem_sfc.inc
  var/da/da_obs_io/da_scan_obs_chem_sfc.inc
Labels: WRFDA, release-v4.4

#1725 Added missing namelist options for v4.4, removed anything pertaining to V3
  run/README.namelist
Labels: README, release-v4.4
