Repository wrf-model/WRF, pull requests merged in 2022-01, with the labels that each got.

#1593 Remove repetitive code in module_sf_urban.F
  phys/module_sf_urban.F
Labels: PHYSICS, Enhancement, Develop Branch

#1552 Parallel netcdf-4 IO option
  Makefile
  Registry/Registry.EM_COMMON
  arch/Config.pl
  arch/md_calls.inc
  arch/postamble
  arch/preamble
  configure
  doc/README.netcdf4par
  external/Makefile
  external/io_netcdfpar/Makefile
  external/io_netcdfpar/diffwrf.F90
  external/io_netcdfpar/ext_ncdpar_get_dom_ti.code
  external/io_netcdfpar/ext_ncdpar_get_var_td.code
  external/io_netcdfpar/ext_ncdpar_get_var_ti.code
  external/io_netcdfpar/ext_ncdpar_put_dom_ti.code
  external/io_netcdfpar/ext_ncdpar_put_var_td.code
  external/io_netcdfpar/ext_ncdpar_put_var_ti.code
  external/io_netcdfpar/field_routines.F90
  external/io_netcdfpar/module_wrfsi_static.F90
  external/io_netcdfpar/transpose.code
  external/io_netcdfpar/wrf_io.F90
  frame/md_calls.m4
  frame/module_io.F
  share/mediation_integrate.F
  share/module_io_domain.F
  share/output_wrf.F
  share/wrf_ext_write_field.F
Labels: Enhancement, Develop Branch, Infrastructure: OK

#1628 Fix PBL + LES logic initialization - redux
  share/module_check_a_mundo.F
Labels: bug, PHYSICS, release-v4.3.3

#1629 Turn off vertical mixing enhancement at layer kts, where should be == 0 - redux
  chem/dry_dep_driver.F
Labels: bug, WRF Chem, release-v4.3.3

#1630 Output photolysis rates for NO2 and O1D to history stream by default - redux
  Registry/registry.chem
Labels: WRF Chem, Enhancement, release-v4.3.3

#1631 Control use of ISORROPIA 2.1 in chem_opts = 100,108,109 by namelist- redux
  Registry/registry.chem
  chem/aerosol_driver.F
  chem/module_aerosols_soa_vbs.F
Labels: WRF Chem, Enhancement, release-v4.3.3

#1634 fix WRFDA build for Parallel netcdf-4 IO
  Registry/Registry.EM_COMMON.var
Labels: bug, WRFDA, Develop Branch

#1632 Bug fix for TAMDAR T VarBC
  var/da/da_varbc_tamdar/da_varbc_tamdar_tl.inc
  var/da/da_varbc_tamdar/da_varbc_tamdar_update.inc
Labels: bug, WRFDA, Develop Branch

#1641 Sync with NoahMP Github version with all NoahMP updates since v4.3
  Registry/Registry.EM_COMMON
  Registry/registry.noahmp
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  phys/module_diag_misc.F
  phys/module_diagnostics_driver.F
  phys/module_physics_init.F
  phys/module_sf_noahmp_glacier.F
  phys/module_sf_noahmp_groundwater.F
  phys/module_sf_noahmpdrv.F
  phys/module_sf_noahmplsm.F
  phys/module_surface_driver.F
  run/MPTABLE.TBL
  run/README.namelist
  run/SOILPARM.TBL
Labels: PHYSICS, Enhancement, Develop Branch

#1642 Bug fix for radar_rf_opt=2
  var/da/da_radar/da_get_innov_vector_radar.inc
  var/da/da_radar/da_radzicevar.inc
  var/da/da_radar/da_radzicevar_upper_f.inc
  var/da/da_radar/da_transform_xtoy_radar.inc
  var/da/da_radar/da_transform_xtoy_radar_adj.inc
  var/da/da_setup_structures/da_setup_obs_structures_radar.inc
  var/da/da_setup_structures/da_setup_structures.f90
Labels: bug, WRFDA, Develop Branch

#1645 Fix for Intel: HSW/BDW config option
  arch/configure.defaults
Labels: bug, Develop Branch

#1625 Run-time option for climate GHG for radiation
  Makefile
  Registry/Registry.EM_COMMON
  clean
  dyn_em/module_first_rk_step_part1.F
  dyn_em/start_em.F
  main/depend.common
  phys/module_physics_init.F
  phys/module_ra_cam.F
  phys/module_ra_cam_support.F
  phys/module_ra_clWRF_support.F
  phys/module_ra_rrtm.F
  phys/module_ra_rrtmg_lw.F
  phys/module_ra_rrtmg_lwf.F
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
  phys/module_ra_sw.F
  phys/module_radiation_driver.F
  run/README.namelist
  share/module_check_a_mundo.F
  share/output_wrf.F
Labels: PHYSICS, Enhancement, Develop Branch

#1638 Fix runtime error when using sf_surface_mosaic = 1 with use_wudapt_lcz = 0
  dyn_em/module_first_rk_step_part1.F
  phys/module_sf_noahdrv.F
  phys/module_surface_driver.F
Labels: bug, PHYSICS, Develop Branch

#1622 MYNN PBL clouds in photolysis option 4 (TUV)
  Registry/registry.chem
  chem/chem_driver.F
  chem/module_phot_tuv.F
  chem/photolysis_driver.F
  share/module_check_a_mundo.F
Labels: WRF Chem, Enhancement, Develop Branch

#1540 New module firebrand_spotting for WRF-Fire
  Registry/Registry.EM_COMMON
  Registry/registry.fire
  dyn_em/depend.dyn_em
  dyn_em/solve_em.F
  dyn_em/start_em.F
  main/depend.common
  phys/Makefile
  phys/module_firebrand_spotting.F
  phys/module_firebrand_spotting_mpi.F
Labels: New Feature, WRF Fire, Develop Branch

#1543 SFCLAY=1, add shallow water roughness calculation
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  dyn_em/module_initialize_real.F
  dyn_em/nest_init_utils.F
  dyn_em/start_em.F
  phys/module_physics_init.F
  phys/module_sf_sfclayrev.F
  phys/module_surface_driver.F
  run/README.namelist
  share/module_check_a_mundo.F
  share/module_optional_input.F
  test/em_real/examples.namelist
Labels: PHYSICS, New Feature, Develop Branch

#1644 Update HONO, TERP, and CO2 emissions
  Registry/registry.chem
  chem/module_emissions_anthropogenics.F
Labels: WRF Chem, Enhancement, Develop Branch

#1626 After testing with UFS/GFS/FV-3, some tuning knob changes to Thompson-MP and icloud3 (cloud fraction) scheme
  phys/module_mp_thompson.F
  phys/module_ra_rrtmg_lw.F
  phys/module_ra_rrtmg_lwf.F
  phys/module_ra_rrtmg_sw.F
  phys/module_ra_rrtmg_swf.F
  phys/module_radiation_driver.F
Labels: PHYSICS, Enhancement, Develop Branch

#1616 Thompson AA enhancements: BC aerosol, biomass burning emissions, and …
  Registry/Registry.EM_COMMON
  Registry/registry.new3d_wif
  dyn_em/module_em.F
  dyn_em/module_first_rk_step_part1.F
  dyn_em/module_initialize_real.F
  dyn_em/solve_em.F
  dyn_em/start_em.F
  main/real_em.F
  phys/module_bl_mynn.F
  phys/module_microphysics_driver.F
  phys/module_mp_thompson.F
  phys/module_pbl_driver.F
  phys/module_physics_init.F
  phys/module_radiation_driver.F
  share/input_wrf.F
  share/mediation_integrate.F
  share/module_check_a_mundo.F
  share/module_optional_input.F
Labels: PHYSICS, Enhancement, Develop Branch

#1652 Fix 4dvar build failure after commit 8b5bfe59
  var/build/da_name_space.pl
Labels: bug, WRFDA, Develop Branch

#1547 Adding the WRF-Solar EPS model
  Makefile
  Registry/Registry.EM_COMMON
  Registry/registry.dimspec
  Registry/registry.stoch
  clean
  dyn_em/module_first_rk_step_part1.F
  dyn_em/module_first_rk_step_part2.F
  dyn_em/module_stoch.F
  dyn_em/solve_em.F
  phys/module_microphysics_driver.F
  phys/module_pbl_driver.F
  phys/module_ra_farms.F
  phys/module_radiation_driver.F
  phys/module_shallowcu_driver.F
  phys/module_shcu_deng.F
  phys/module_surface_driver.F
  run/README.namelist
  run/STOCHPERT.TBL
  share/module_check_a_mundo.F
Labels: PHYSICS, New Feature, Develop Branch

#1651 BF: NETCDFPAR "Error" in build log when option not used
  Makefile
  arch/Config.pl
  arch/configure.defaults
  configure
Labels: bug, Develop Branch

#1662 BF firebrand array index must be integer
  phys/module_firebrand_spotting.F
Labels: bug, PHYSICS, release-v4.4
