Repository wrf-model/WRF, pull requests merged in 2022-12, with the labels that each got.

#1774 Enhancements for AHI radiance DA
  Registry/registry.var
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_monitor/da_rad_diags.f90
  var/da/da_radiance/da_allocate_rad_iv.inc
  var/da/da_radiance/da_deallocate_radiance.inc
  var/da/da_radiance/da_get_innov_vector_crtm.inc
  var/da/da_radiance/da_initialize_rad_iv.inc
  var/da/da_radiance/da_qc_ahi.inc
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_radiance1.f90
  var/da/da_radiance/da_radiance_init.inc
  var/da/da_radiance/da_read_obs_netcdf4ahi_jaxa.inc
  var/da/da_radiance/da_write_iv_rad_ascii.inc
  var/da/da_radiance/module_radiance.f90
  var/run/ahi_info
  var/run/radiance_info/himawari-8-ahi.info
Labels: WRFDA, Develop Branch

#1775 LFC, CAPE, and CIN Calculation Improvement
  phys/module_diag_functions.F
Labels: release-v4.4.2

#1773 Matching wrf results aarch64 x86 with gcc10.2
  arch/configure.defaults
  phys/module_cu_tiedtke.F
  phys/module_sf_myjsfc.F
Labels: Develop Branch

#1783 Add missing oops for CLM plus urban check
  share/module_check_a_mundo.F
Labels: release-v4.4.2

#1791 Fix declaration for QSFC to INOUT variable
  phys/module_sf_sfclay.F
  phys/module_sf_sfclayrev.F
Labels: release-v4.4.2

#1765 Fix undefined behavior in RSL_LITE
  external/RSL_LITE/rsl_bcast.c
  external/RSL_LITE/rsl_lite.h
Labels: release-v4.4.2

#1795 updated top-level README and version_decl for V4.4.2
  README
  inc/version_decl
Labels: release-v4.4.2
