Repository wrf-model/WRF, pull requests merged in 2023-01, with the labels that each got.

#1799 Use GFS total column ozone in TUV photolysis
  Registry/Registry.EM_COMMON
  Registry/registry.chem
  chem/chem_driver.F
  chem/module_phot_tuv.F
  chem/photolysis_driver.F
Labels: WRF Chem, Enhancement, Develop Branch

#1802 Fixed small indexing error of rhoair in ISHMAEL MP scheme
  phys/module_mp_jensen_ishmael.F
Labels: Develop Branch

#1801 Updates and fixes to module_firebrand_spotting
  Registry/registry.fire
  dyn_em/solve_em.F
  dyn_em/start_em.F
  phys/module_firebrand_spotting.F
  phys/module_firebrand_spotting_mpi.F
Labels: Develop Branch

#1787 Adds ADIOS2, high performance parallel I/O backend to WRF [after fixes]
  Registry/Registry.CONVERT
  Registry/Registry.EM_COMMON
  Registry/Registry.EM_COMMON.var
  Registry/registry.io_boilerplate
  arch/Config.pl
  arch/postamble
  arch/preamble
  configure
  doc/README.adios2
  external/Makefile
  external/io_adios2/Makefile
  external/io_adios2/ext_adios2_get_dom_ti.code
  external/io_adios2/ext_adios2_get_var_td.code
  external/io_adios2/ext_adios2_get_var_ti.code
  external/io_adios2/ext_adios2_put_dom_ti.code
  external/io_adios2/ext_adios2_put_var_td.code
  external/io_adios2/ext_adios2_put_var_ti.code
  external/io_adios2/field_routines.F90
  external/io_adios2/transpose.code
  external/io_adios2/wrf_io.F90
  external/ioapi_share/wrf_status_codes.h
  frame/md_calls.m4
  frame/module_io.F
  share/module_io_domain.F
  share/output_wrf.F
  share/wrf_ext_write_field.F
Labels: New Feature, Develop Branch

#1809 Update to WRF-Hydro v5.3.0
  hydro/.version
  hydro/Data_Rec/module_namelist.F
  hydro/Data_Rec/namelist.inc
  hydro/Data_Rec/rt_include.inc
  hydro/HYDRO_drv/module_HYDRO_drv.F
  hydro/MPP/module_mpp_GWBUCKET.F
  hydro/MPP/module_mpp_ReachLS.F
  hydro/Makefile
  hydro/OrchestratorLayer/config.f90
  hydro/OrchestratorLayer/io_manager.f90
  hydro/OrchestratorLayer/orchestrator.f90
  hydro/Rapid_routing/.gitignore
  hydro/Rapid_routing/.rapid_init.F90.swp
  hydro/Rapid_routing/LICENSE
  hydro/Rapid_routing/README
  hydro/Rapid_routing/makefile
  hydro/Rapid_routing/makefile.cpl
  hydro/Rapid_routing/makefile.orig
  hydro/Rapid_routing/rapid_namelist
  hydro/Rapid_routing/rapid_script.sh
  hydro/Routing/Noah_distr_routing.F
  hydro/Routing/Noah_distr_routing_overland.F
  hydro/Routing/Noah_distr_routing_subsurface.F
  hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_properties.F
  hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F
  hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_properties.F
  hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_state.F
  hydro/Routing/Reservoirs/reservoir_tests.F
  hydro/Routing/Subsurface/module_subsurface_properties.F
  hydro/Routing/module_GW_baseflow.F
  hydro/Routing/module_HYDRO_io.F
  hydro/Routing/module_HYDRO_utils.F
  hydro/Routing/module_NWM_io.F
  hydro/Routing/module_NWM_io_dict.F
  hydro/Routing/module_RT.F
  hydro/Routing/module_channel_routing.F
  hydro/Routing/module_lsm_forcing.F
  hydro/arc/Makefile.Noah
  hydro/arc/Makefile.NoahMP
  hydro/arc/macros.gordon
  hydro/arc/macros.mpp.IBM.xlf90_r
  hydro/arc/macros.mpp.gfort
  hydro/arc/macros.mpp.ifort
  hydro/arc/macros.mpp.ifort.luna
  hydro/arc/macros.mpp.ifort.omp
  hydro/arc/macros.mpp.ifort.summit_has
  hydro/arc/macros.mpp.ifort.theia
  hydro/arc/macros.mpp.intel.cray_xc
  hydro/arc/macros.mpp.linux
  hydro/arc/macros.mpp.mpiifort
  hydro/arc/macros.seq.IBM.xlf90_r
  hydro/arc/macros.seq.gfort
  hydro/arc/macros.seq.ifort
  hydro/arc/macros.seq.linux
  hydro/arc/macros.yellowstone
  hydro/template/HYDRO/hydro.namelist
  hydro/template/NoahMP/namelist.hrldas
Labels: Develop Branch

#1806 Add scale-aware to the new Tiedtke cu scheme as an option
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/module_cu_ntiedtke.F
  phys/module_cumulus_driver.F
  run/README.namelist
Labels: Develop Branch

#1788 MYNN-EDMF Update from CCPP to WRF
  Registry/Registry.EM_COMMON
  Registry/registry.chem
  chem/chemics_init.F
  chem/dry_dep_driver.F
  dyn_em/module_big_step_utilities_em.F
  dyn_em/module_first_rk_step_part1.F
  dyn_em/solve_em.F
  main/depend.common
  phys/Makefile
  phys/module_bl_fogdes.F
  phys/module_bl_mynn.F
  phys/module_bl_mynn_common.F
  phys/module_bl_mynn_wrapper.F
  phys/module_pbl_driver.F
  phys/module_physics_addtendc.F
  phys/module_physics_init.F
  phys/module_sf_fogdes.F
  phys/module_shcu_camuwshcu.F
  share/module_check_a_mundo.F
  wrftladj/module_first_rk_step_part1_ad.F
  wrftladj/module_first_rk_step_part1_tl.F
  wrftladj/module_pbl_driver_ad.F
  wrftladj/module_pbl_driver_tl.F
  wrftladj/module_physics_addtendc_tl.F
  wrftladj/solve_em_ad.F
  wrftladj/solve_em_tl.F
Labels: Develop Branch

#1766 Add support for NVIDIA HPC SDK Compilers on ARM
  arch/configure.defaults
Labels: Develop Branch

#1808 MP38 Thompson 2-mom graupel/hail (prev #1667, #1728)
  Registry/Registry.EM_COMMON
  phys/module_diag_nwp.F
  phys/module_diagnostics_driver.F
  phys/module_microphysics_driver.F
  phys/module_mp_thompson.F
  phys/module_physics_init.F
Labels: Develop Branch

#1810 WRF-urban bug fix for roof longwave calculation in bep_bem
  phys/module_sf_bep_bem.F
Labels: Develop Branch

#1803 Fix an error with O31D exceeding vertical dimension kte
  phys/module_ra_rrtmg_lw.F
Labels: Develop Branch

#1781 K epsilon theta^2, new PBL closure, Zonato et al, 2022
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/Makefile
  phys/module_bl_keps.F
  phys/module_pbl_driver.F
  phys/module_physics_addtendc.F
Labels: Develop Branch, WPRP approved

#1684 Amd aocc support
  arch/configure.defaults
Labels: New Feature, Develop Branch

#1813 BUG FIX: chem_opt = 201, 202 ph_diag
  chem/aerosol_driver.F
  chem/cloudchem_driver.F
  chem/module_mosaic_cloudchem.F
  chem/module_mosaic_driver.F
  chem/module_mosaic_therm.F
Labels: bug, WRF Chem
