Repository wrf-model/WRF, pull requests merged in 2024-10, with the labels that each got.

#2112 fixed redistribution between GOCART dust/sea salt and MOZAIC bins
  chem/module_optical_averaging.F
  chem/optical_driver.F
Labels: WRF Chem, release-v4.6.1

#2057 Case insensitive F90 compile rule
  arch/postamble
Labels: Develop Branch

#2107 Corrected end date for em_b_wave test case
  test/em_b_wave/namelist.input
Labels: release-v4.6.1

#2110 Update how fogdes identifies land use type
  phys/module_sf_fogdes.F
  phys/module_surface_driver.F
Labels: release-v4.6.1

#2070 Breakout deallocation calls into simpler smaller files
  clean
  frame/CMakeLists.txt
  frame/Makefile
  frame/module_domain.F
  inc/.gitignore
  main/depend.common
  tools/CMakeLists.txt
  tools/gen_allocs.c
  tools/protos.h
  var/build/da.make
  var/build/da_name_space.pl
  var/build/depend.txt
Labels: compile-tests

#2101 Shortwave radiation balance at the wall missing reflected direct and diffuse radiation reflection from the wall terms.
  phys/module_sf_urban.F
Labels: release-v4.6.1
