Repository wrf-model/WRF, pull requests merged in 2024-02, with the labels that each got.

#1996 Syncing MYNN-EDMF + bug fix
  phys/module_bl_mynn.F
Labels: Develop Branch

#1812 BLD: Fix compile on Cygwin.
  configure
  doc/README.cygwin.md
  doc/README.netcdf4par
Labels: Develop Branch

#1926 Truncated Gaussian Heat and Smoke Release Formulation for WRF-Fire
  Registry/registry.fire
  phys/module_fr_fire_atm.F
  phys/module_fr_fire_driver.F
  phys/module_fr_fire_driver_wrf.F
Labels: Develop Branch

#1989 Add shared physics gwdo
  arch/postamble
  arch/preamble
  clean
  main/depend.common
  phys/Makefile
  phys/module_bl_gwdo.F
  phys/module_pbl_driver.F
  phys/physics_mmm/bl_gwdo.F90
  wrftladj/module_pbl_driver_ad.F
Labels: Develop Branch

#1991 Shared physics YSU PBL
  main/depend.common
  phys/Makefile
  phys/module_bl_ysu.F
  phys/module_pbl_driver.F
  phys/module_physics_init.F
  phys/physics_mmm/bl_ysu.F90
Labels: Develop Branch

#1993 Shared physics wsm6
  main/depend.common
  phys/Makefile
  phys/module_microphysics_driver.F
  phys/module_mp_wsm6.F
  phys/module_physics_init.F
  phys/physics_mmm/module_libmassv.F90
  phys/physics_mmm/mp_radar.F90
  phys/physics_mmm/mp_wsm6.F90
  phys/physics_mmm/mp_wsm6_effectRad.F90
  share/module_model_constants.F
Labels: Develop Branch

#1994 Shared physics nTiedtke
  main/depend.common
  phys/Makefile
  phys/module_cu_ntiedtke.F
  phys/module_cumulus_driver.F
  phys/physics_mmm/cu_ntiedtke.F90
Labels: Develop Branch

#1826 The WRF-SoilN-chem: a dynamic ammonia emission model
  Registry/Registry.EM_COMMON
  Registry/registry.chem
  chem/chem_driver.F
  chem/emissions_driver.F
Labels: WRF Chem, Develop Branch

#2000 Bug fix for chem_opt=100 (vbs_het), racm_soa_vbs_het_kpp initialization
  Registry/registry.chem
  chem/chemics_init.F
  chem/module_aerosols_soa_vbs_het.F
Labels: bug, WRF Chem, Develop Branch

#2003 Fix compile on Cygwin
  configure
  doc/README.cygwin.md
  doc/README.netcdf4par
Labels: Develop Branch

#1942 Resolves building issues (WRF/WRF-chem) with Intel compilers (ifx/icx)
  chem/KPP/kpp/kpp-2.1/src/code.c
  chem/KPP/kpp/kpp-2.1/src/code.h
  chem/KPP/kpp/kpp-2.1/src/code_c.c
  chem/KPP/kpp/kpp-2.1/src/code_f77.c
  chem/KPP/kpp/kpp-2.1/src/code_f90.c
  chem/KPP/kpp/kpp-2.1/src/code_matlab.c
  chem/KPP/kpp/kpp-2.1/src/gdata.h
  chem/KPP/kpp/kpp-2.1/src/gen.c
  chem/KPP/kpp/kpp-2.1/src/gen_org.c
  chem/KPP/kpp/kpp-2.1/src/kpp.c
  chem/KPP/kpp/kpp-2.1/src/scan.h
  chem/KPP/kpp/kpp-2.1/src/scan.l
  chem/KPP/kpp/kpp-2.1/src/scan.y
  chem/KPP/util/wkc/Makefile
  chem/KPP/util/wkc/change_chem_Makefile.c
  chem/KPP/util/wkc/compare_kpp_to_species.c
  chem/KPP/util/wkc/gen_kpp.c
  chem/KPP/util/wkc/gen_kpp_args_to_Update_Rconst.c
  chem/KPP/util/wkc/gen_kpp_interf_utils.c
  chem/KPP/util/wkc/gen_kpp_interface.c
  chem/KPP/util/wkc/gen_kpp_mech_dr.c
  chem/KPP/util/wkc/gen_kpp_utils.c
  chem/KPP/util/wkc/get_kpp_chem_specs.c
  chem/KPP/util/wkc/get_wrf_jvals.c
  chem/KPP/util/wkc/get_wrf_radicals.c
  chem/KPP/util/wkc/kpp_data.c
  chem/KPP/util/wkc/protos_kpp.h
  chem/KPP/util/wkc/registry_kpp.c
  chem/KPP/util/write_decomp/integr_edit.c
  compile
  external/RSL_LITE/rsl_bcast.c
  tools/Makefile
  tools/gen_interp.c
  tools/gen_irr_diag.c
  tools/gen_wrf_io.c
  tools/reg_parse.c
Labels: WRF Chem, Develop Branch

#2005 Fix AHE option 2 and a problem with mosaic
  dyn_em/module_first_rk_step_part1.F
  dyn_em/module_initialize_real.F
  main/depend.common
  phys/module_pbl_driver.F
  phys/module_sf_noahdrv.F
  phys/module_surface_driver.F
Labels: Develop Branch

#2013 CMake build of diffwrf binaries
  CMakeLists.txt
  external/io_int/CMakeLists.txt
  external/io_netcdf/CMakeLists.txt
  external/io_netcdfpar/CMakeLists.txt
Labels: Develop Branch

#2010 Makes mp_zero_out affect only the 'moist' array. New separate flags for scalar/chem/tracer
  Registry/Registry.EM_COMMON
  dyn_em/solve_em.F
  run/README.namelist
  wrftladj/solve_em_ad.F
  wrftladj/solve_em_tl.F
Labels: Develop Branch

#2015 Print parameters used in auto_levels_opt = 2
  dyn_em/module_initialize_real.F
Labels: Develop Branch
