Repository wrf-model/WRF, pull requests merged in 2024-01, with the labels that each got.

#1911 Removal of redundant code files wrf_status_codes.h, wrf_io_flags.h, io_int_idx_tags.h
  external/io_grib1/Makefile
  external/io_grib1/wrf_status_codes.h
  external/io_grib_share/Makefile
  external/io_grib_share/wrf_io_flags.h
  external/io_grib_share/wrf_status_codes.h
  external/io_int/io_int.F90
  external/io_int/io_int_idx.c
  external/io_int/makefile
  external/ioapi_share/wrf_status_codes.h
  frame/module_internal_header_util.F
  frame/module_io_quilt_old.F
  inc/intio_tags.h
Labels: Develop Branch

#1976 Bug fix for erroneous syntax in dyn_em/module_first_rk_step_part1.F
  dyn_em/module_first_rk_step_part1.F
Labels: Develop Branch

#1973 Bug fix in gen_allocs to use correct conditional compilation logic on allocatables vs pointers
  tools/gen_allocs.c
Labels: Develop Branch

#1978 Improved ignores
  .gitignore
Labels: Develop Branch

#1979 Enable WRFDA's compilation with RTTOV and HDF5 libs on Derecho
  compile
Labels: WRFDA, Develop Branch

#1977 Update g2lib png encode/decode to use correct png_voidp define
  external/io_grib2/g2lib/dec_png.c
  external/io_grib2/g2lib/enc_png.c
Labels: Develop Branch

#1974 Add error checks in registry to catch code generation failure
  tools/registry.c
Labels: Develop Branch

#1910 Adjust #defines to accommodate future CMake build
  dyn_em/module_advect_em.F
  external/atm_ocn/cmpcomm.F
  external/io_adios2/wrf_io.F90
  external/io_netcdf/wrf_io.F90
  external/io_netcdfpar/wrf_io.F90
  external/io_pnetcdf/wrf_io.F90
  frame/module_configure.F
  phys/module_mp_SBM_polar_radar.F
  phys/module_mp_fast_sbm.F
Labels: Develop Branch

#1868 Adding Scott and Burgan (2005) 40 Fuel Models for WRF-Fire
  phys/module_fr_fire_phys.F
  test/em_fire/namelist.fire.sb40
  test/em_fire/namelist.fire_fmc.sb40
Labels: Develop Branch

#1938 Updates to MYNN-EDMF
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  main/depend.common
  phys/Makefile
  phys/ccpp_kind_types.F
  phys/module_bl_mynn.F
  phys/module_bl_mynn_common.F
  phys/module_bl_mynn_wrapper.F
  phys/module_pbl_driver.F
  phys/module_radiation_driver.F
Labels: Develop Branch

#1924 Remove arbitrary limiting of heat fluxes
  phys/module_sf_sfclay.F
  phys/module_sf_sfclayrev.F
Labels: Develop Branch

#1975 Add the ability for registry code generation to be out of source
  tools/reg_parse.c
Labels: Develop Branch

#1983 Add the capability for assimilating GOES-ABI radiance data
  Registry/registry.var
  var/build/depend.txt
  var/da/da_define_structures/da_define_structures.f90
  var/da/da_monitor/da_rad_diags.f90
  var/da/da_radiance/da_allocate_rad_iv.inc
  var/da/da_radiance/da_deallocate_radiance.inc
  var/da/da_radiance/da_get_innov_vector_crtm.inc
  var/da/da_radiance/da_get_innov_vector_rttov.inc
  var/da/da_radiance/da_get_sat_angles.inc
  var/da/da_radiance/da_get_sat_angles_1d.inc
  var/da/da_radiance/da_get_solar_angles.inc
  var/da/da_radiance/da_get_solar_angles_1d.inc
  var/da/da_radiance/da_initialize_rad_iv.inc
  var/da/da_radiance/da_qc_goesabi.inc
  var/da/da_radiance/da_qc_rad.inc
  var/da/da_radiance/da_radiance.f90
  var/da/da_radiance/da_radiance1.f90
  var/da/da_radiance/da_radiance_init.inc
  var/da/da_radiance/da_read_obs_ncgoesabi.inc
  var/da/da_radiance/da_rttov.f90
  var/da/da_radiance/da_setup_radiance_structures.inc
  var/da/da_radiance/da_write_iv_rad_ascii.inc
  var/da/da_radiance/da_write_oa_rad_ascii.inc
  var/da/da_radiance/module_radiance.f90
  var/da/da_setup_structures/da_setup_obs_structures.inc
  var/da/da_setup_structures/da_setup_structures.f90
  var/da/da_tools/da_llxy_1d.inc
  var/da/da_tools/da_llxy_default_1d.inc
  var/da/da_tools/da_llxy_global_1d.inc
  var/da/da_tools/da_llxy_kma_global_1d.inc
  var/da/da_tools/da_llxy_latlon_1d.inc
  var/da/da_tools/da_llxy_lc_1d.inc
  var/da/da_tools/da_llxy_merc_1d.inc
  var/da/da_tools/da_llxy_ps_1d.inc
  var/da/da_tools/da_llxy_rotated_latlon_1d.inc
  var/da/da_tools/da_llxy_wrf_1d.inc
  var/da/da_tools/da_togrid_1d.inc
  var/da/da_tools/da_tools.f90
  var/run/VARBC.in
  var/run/radiance_info/goes-16-abi.info
  var/run/radiance_info/goes-17-abi.info
Labels: WRFDA, Develop Branch

#1985 Fix registry description for settling velocity of bin 5
  Registry/registry.chem
Labels: WRF Chem, Develop Branch

#1876 Add 3-moment option to NSSL microphysics (plus other minor scheme updates)
  Registry/Registry.EM_COMMON
  Registry/registry.var
  Registry/registry.wrfplus
  chem/chemics_init.F
  doc/README.NSSLmp
  dyn_em/module_advect_em.F
  dyn_em/solve_em.F
  dyn_em/start_em.F
  phys/module_diag_nwp.F
  phys/module_diagnostics_driver.F
  phys/module_microphysics_driver.F
  phys/module_mp_nssl_2mom.F
  phys/module_physics_init.F
  run/README.namelist
  share/module_check_a_mundo.F
  wrftladj/module_microphysics_driver_ad.F
  wrftladj/module_microphysics_driver_tl.F
Labels: Develop Branch

#1969 Update urban LCZ parameter table with more reasonable values
  run/URBPARM_LCZ.TBL
Labels: Develop Branch

#1944 Add three new wind farm parameterizations and their ensembles
  Registry/Registry.EM_COMMON
  dyn_em/module_first_rk_step_part1.F
  phys/Makefile
  phys/module_pbl_driver.F
  phys/module_physics_init.F
  phys/module_wind_mav.F
  run/README.namelist
Labels: Develop Branch

#1959 Use Qv or specific humidity in interpolation if they are available
  Registry/Registry.EM_COMMON
  dyn_em/module_initialize_real.F
  run/README.namelist
Labels: Develop Branch

#1963 add salinity effect in sfclay and sfclayrev
  phys/module_sf_sfclay.F
  phys/module_sf_sfclayrev.F
  phys/module_surface_driver.F
Labels: Develop Branch

#1950 Rectify many of the missing dependencies
  main/depend.common
Labels: Develop Branch

#1999 Add missing dependency module_wind_mav to module_physics_init
  main/depend.common
Labels: Develop Branch

#1998 Move shalwater_init to physics_init
  phys/module_physics_init.F
  phys/module_sf_sfclayrev.F
Labels: Develop Branch
