Repository wrf-model/WRF, pull requests merged in 2025-01, with the labels that each got.

#2089 CMake WRFPLUS
  CMakeLists.txt
  cmake/wrf_case_setup.cmake
  main/CMakeLists.txt
  wrftladj/CMakeLists.txt
Labels: Develop Branch

#2126 Add manage externals to access MMM-physics repo
  CMakeLists.txt
  arch/Externals.cfg
  phys/Makefile
  phys/physics_mmm/bl_gwdo.F90
  phys/physics_mmm/bl_ysu.F90
  phys/physics_mmm/cu_ntiedtke.F90
  phys/physics_mmm/module_libmassv.F90
  phys/physics_mmm/mp_radar.F90
  phys/physics_mmm/mp_wsm6.F90
  phys/physics_mmm/mp_wsm6_effectRad.F90
  phys/physics_mmm/sf_sfclayrev.F90
  tools/manage_externals/.gitignore
  tools/manage_externals/LICENSE.txt
  tools/manage_externals/README.md
  tools/manage_externals/README_FIRST
  tools/manage_externals/checkout_externals
  tools/manage_externals/manic/__init__.py
  tools/manage_externals/manic/checkout.py
  tools/manage_externals/manic/externals_description.py
  tools/manage_externals/manic/externals_status.py
  tools/manage_externals/manic/global_constants.py
  tools/manage_externals/manic/repository.py
  tools/manage_externals/manic/repository_factory.py
  tools/manage_externals/manic/repository_git.py
  tools/manage_externals/manic/repository_svn.py
  tools/manage_externals/manic/sourcetree.py
  tools/manage_externals/manic/utils.py
  tools/manage_externals/version.txt
Labels: Develop Branch, compile-tests

#2108 CMake Fix split command flags to be correctly populated
  CMakeLists.txt
  arch/configure_reader.py
Labels: Develop Branch

#2099 Consistent double precision definitions
  CMakeLists.txt
  Makefile
  arch/Config.pl
  arch/md_calls.inc
  arch/postamble
  chem/module_phot_tuv.F
  configure
  dyn_em/module_big_step_utilities_em.F
  external/RSL_LITE/module_dm.F
  external/io_int/io_int.F90
  external/ioapi_share/makefile
  external/ioapi_share/wrf_io_flags.h
  frame/md_calls.m4
  frame/module_clear_halos.F
  frame/module_cpl_oasis3.F
  phys/ccpp_kind_types.F
  phys/module_mp_ntu.F
  phys/module_mp_wdm5.F
  phys/module_mp_wdm6.F
  phys/module_mp_wdm7.F
  phys/module_mp_wsm3.F
  phys/module_mp_wsm3_accel.F
  phys/module_mp_wsm5.F
  phys/module_mp_wsm5_accel.F
  phys/module_mp_wsm7.F
  phys/module_ra_cam_support.F
  phys/module_ra_goddard.F
  phys/module_ra_rrtmg_aero_optical_util_cmaq.F
  phys/module_ra_rrtmg_lw.F
  share/module_check_a_mundo.F
  tools/gen_allocs.c
  var/da/da_control/da_control.f90
  var/da/da_obs_io/da_read_obs_bufr.inc
  var/da/da_par_util/da_par_util1.f90
  var/da/da_par_util/da_proc_maxmin_combine.inc
  var/da/da_par_util/da_proc_stats_combine.inc
  var/da/da_radiance/gsi_kinds.f90
  wrftladj/module_big_step_utilities_em_ad.F
  wrftladj/module_big_step_utilities_em_tl.F
Labels: Develop Branch

#2146 hydro: reservoir, reach lakes, style guide cleanup
  hydro/CPL/WRF_cpl/module_wrf_HYDRO.F90
  hydro/CPL/WRF_cpl/module_wrf_HYDRO_downscale.F90
  hydro/CPL/WRF_cpl/wrf_drv_HYDRO.F90
  hydro/Data_Rec/module_RT_data.F90
  hydro/Data_Rec/module_gw_gw2d_data.F90
  hydro/Data_Rec/module_namelist.F90
  hydro/HYDRO_drv/module_HYDRO_drv.F90
  hydro/IO/netcdf_layer.F90
  hydro/MPP/CPL_WRF.F90
  hydro/MPP/module_mpp_GWBUCKET.F90
  hydro/MPP/module_mpp_ReachLS.F90
  hydro/MPP/mpp_land.F90
  hydro/OrchestratorLayer/config.F90
  hydro/Routing/Noah_distr_routing.F90
  hydro/Routing/Reservoirs/Level_Pool/module_levelpool.F90
  hydro/Routing/Reservoirs/Level_Pool/module_levelpool_properties.F90
  hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid.F90
  hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F90
  hydro/Routing/module_GW_baseflow.F90
  hydro/Routing/module_HYDRO_io.F90
  hydro/Routing/module_HYDRO_utils.F90
  hydro/Routing/module_NWM_io.F90
  hydro/Routing/module_RT.F90
  hydro/Routing/module_UDMAP.F90
  hydro/Routing/module_channel_routing.F90
  hydro/Routing/module_date_utilities_rt.F90
  hydro/Routing/module_gw_gw2d.F90
  hydro/Routing/module_lsm_forcing.F90
  hydro/Routing/module_reservoir_routing.F90
  hydro/nudging/module_date_utils_nudging.F90
  hydro/nudging/module_nudging_io.F90
  hydro/nudging/module_nudging_utils.F90
  hydro/nudging/module_stream_nudging.F90
  hydro/template/HYDRO/hydro.namelist
  hydro/template/NoahMP/namelist.hrldas
  hydro/utils/module_hydro_stop.F90
Labels: Develop Branch

#2153 Bug fix for overwriting of LCZ urban cells in LU_INDEX with default USGS urban category.
  dyn_em/module_initialize_real.F
Labels: Develop Branch

#2144 RCON Microphysics
  Registry/Registry.EM_COMMON
  Registry/registry.var
  dyn_em/module_initialize_real.F
  dyn_em/solve_em.F
  main/depend.common
  main/real_em.F
  phys/Makefile
  phys/module_microphysics_driver.F
  phys/module_mp_rcon.F
  phys/module_physics_init.F
  run/README.namelist
  share/module_check_a_mundo.F
Labels: Develop Branch

#2018 CMake Chem and Chem+KPP Build
  CMakeLists.txt
  chem/CMakeLists.txt
  chem/KPP/CMakeLists.txt
  chem/KPP/compile_wkc
  chem/KPP/kpp/kpp-2.1/CMakeLists.txt
  chem/KPP/util/wkc/CMakeLists.txt
  chem/KPP/util/wkc/gen_kpp.c
  chem/KPP/util/wkc/protos_kpp.h
  chem/KPP/util/wkc/tuv_kpp.c
  chem/KPP/util/write_decomp/CMakeLists.txt
  chem/KPP/util/write_decomp/Makefile
  chem/KPP/util/write_decomp/integr_edit.c
  chem/chem_driver.F
  tools/CMakeLists.txt
  tools/data.h
  tools/registry.c
Labels: Develop Branch, Retest

#2120 Correction of stability functions for the tke-epsilon-tpe PBL scheme
  phys/module_bl_keps.F
  phys/module_pbl_driver.F
Labels: bug, Develop Branch

#2151 Add incremental analysis update capability
  Registry/Registry.EM_COMMON.var
  Registry/Registry.wrfvar
  Registry/registry.em_shared_collection
  Registry/registry.iau
  dyn_em/module_em.F
  dyn_em/module_first_rk_step_part2.F
  phys/module_physics_addtendc.F
  var/build/da.make
  var/build/depend.txt
  var/da/da_main/da_solve.inc
  var/da/da_main/da_wrfvar_io.f90
  var/da/da_main/da_wrfvar_top.f90
  var/da/da_main/da_write_anaincrements.inc
  var/da/da_transfer_model/da_transfer_xatowrf.inc
Labels: Develop Branch

#2162 CMake Fix RCON Microphysics
  phys/CMakeLists.txt
Labels: Develop Branch
